/**************************************************************************
 * CollectionTarget.java - Mon Sep 12 15:39:20 PDT 2022
 *
 * Copyright (c) SparseWare Inc
 *
 * All rights reserved.
 *
 * Generated by the Sparse Notation(tm) To Java Compiler v1.0
 * Note 1: Code entered after the "//USER_IMPORTS_AND_COMMENTS_MARK{}" comment and before the class declaration will be preserved.
 * Note 2: Code entered out side of the other   comment blocks will be preserved
 * Note 3: If you edit the automatically generated comments and want to preserve your edits remove the //GENERATED_COMMENT{} tags
 */

package com.appnativa.datacollection.spot;

import com.appnativa.spot.*;

//USER_IMPORTS_AND_COMMENTS_MARK{}

public class CollectionTarget extends SPOTSequence {
  //GENERATED_MEMBERS{

//GENERATED_COMMENT{}
  /** name of the widget the set the collection into */ 
  public SPOTPrintableString targetName = new SPOTPrintableString(null, 0, 64, false);

//GENERATED_COMMENT{}
  /** / a URL to use to retrieve data for the collection or collection definition can be a collection: URL */ 
  public SPOTPrintableString dataURL = new SPOTPrintableString();

  public SPOTPrintableString collectionName = new SPOTPrintableString(null, 0, 64, true);

//GENERATED_COMMENT{}
  /** Design: true to register the collection */ 
  public SPOTBoolean registerCollection = new SPOTBoolean(null, false, false );

//GENERATED_COMMENT{}
  /** Design~url: query filter to apply to source collection can be default is a comma separated list of columns (text/csv] or SQL of script code */ 
  public SPOTPrintableString queryURL = new SPOTPrintableString();

//GENERATED_COMMENT{}
  /** Design~url: transform to apply to data */ 
  public SPOTPrintableString transformURL = new SPOTPrintableString();

//GENERATED_COMMENT{}
  /** comma separated list of mappings for column name to field name if target is a formles */ 
  public SPOTPrintableString fieldMapping = new SPOTPrintableString();

//GENERATED_COMMENT{}
  /** whether to replace the column title in the UI markup with the data column title */ 
  public SPOTBoolean replaceTableColumnTitle = new SPOTBoolean(null, false, false );

//GENERATED_COMMENT{}
  /** whether to replace the table columns in the UI markup with the data columns */ 
  public SPOTBoolean replaceTableColumns = new SPOTBoolean(null, false, false );

//GENERATED_COMMENT{}
  /** whether the widgets data should be presented as a registered collection */ 
  public SPOTBoolean projectWidgetAsCollection = new SPOTBoolean(null, false, false );

//GENERATED_COMMENT{}
  /** how item display attributes are treated the when the item's value is set into the widget does not directly support items */ 
  public CItemAttributeHandling itemAttributeHandling = new CItemAttributeHandling(null, null, CItemAttributeHandling.convert_to_html, "convert_to_html", false );

//GENERATED_COMMENT{}
  /** whether the UI should be updated when data changes */ 
  public SPOTBoolean updateWhenDataChanges = new SPOTBoolean(null, false, false );

//GENERATED_COMMENT{}
  /** Design~wheter the source views should be copied into the new collection */ 
  public SPOTBoolean copySourceViews = new SPOTBoolean(null, true, false );

//GENERATED_COMMENT{}
  /** predefined views for this collection */ 
  protected SPOTSet views = null;

//GENERATED_COMMENT{}
  /** initial selectionType can be index,value or linkedData */ 
  public SPOTPrintableString initialSelection = new SPOTPrintableString(null, 0, 64, true);

  public SPOTBoolean generateCategoryViews = new SPOTBoolean(null, false, false );

  protected GroupingInfo grouping = null;

  //}GENERATED_MEMBERS

  //GENERATED_METHODS{

  /**
   * Creates a new optional <code>CollectionTarget</code> object.
   */
  public CollectionTarget()  {
    this(true);
  }

  /**
   * Creates a new <code>CollectionTarget</code> object.
   *
   * @param optional  <code>true</code> if the element is optional; <code>false</code> otherwise)
   */
  public CollectionTarget( boolean optional ) {
    super( optional, false );
    spot_setElements();
  }

  /**
   * Creates a new <code>CollectionTarget</code> object.
   *
   * @param optional  <code>true</code> if the element is optional; <code>false</code> otherwise)
   * @param setElements  <code>true</code> if a call to setElements should be made; <code>false</code> otherwise)
   */
  protected CollectionTarget( boolean optional,boolean setElements ) {
    super( optional, setElements );
  }

  /**
   * Adds elements to the object elements map
   *
   */
  protected void spot_setElements()  {
    this.elementsSizeHint  +=17;
    super.spot_setElements();
    spot_addElement( "targetName", targetName );
    spot_addElement( "dataURL", dataURL );
    dataURL.spot_defineAttribute("mimeType",null);
    dataURL.spot_defineAttribute("method",null);
    dataURL.spot_defineAttribute("deferred",null);
    dataURL.spot_defineAttribute("columnSeparator",null);
    dataURL.spot_defineAttribute("inline",null);
    dataURL.spot_defineAttribute("ldSeparator",null);
    dataURL.spot_defineAttribute("riSeparator",null);
    dataURL.spot_defineAttribute("unescape","false");
    dataURL.spot_defineAttribute("parser",null);
    dataURL.spot_defineAttribute("customProperties",null);
    dataURL.spot_defineAttribute("linkAttributes",null);
    dataURL.spot_defineAttribute("copyType",null);
    dataURL.spot_defineAttribute("monitor","true");
    spot_addElement( "collectionName", collectionName );
    spot_addElement( "registerCollection", registerCollection );
    registerCollection.spot_defineAttribute("title",null);
    registerCollection.spot_defineAttribute("registerViewsByDefault",null);
    registerCollection.spot_defineAttribute("registerViewsList",null);
    registerCollection.spot_defineAttribute("viewsListName",null);
    registerCollection.spot_defineAttribute("viewsListTitle",null);
    registerCollection.spot_defineAttribute("addParentToViewsList",null);
    registerCollection.spot_defineAttribute("viewsListParentTitle",null);
    spot_addElement( "queryURL", queryURL );
    queryURL.spot_defineAttribute("mimeType",null);
    queryURL.spot_defineAttribute("inline",null);
    spot_addElement( "transformURL", transformURL );
    transformURL.spot_defineAttribute("mimeType",null);
    transformURL.spot_defineAttribute("inline",null);
    spot_addElement( "fieldMapping", fieldMapping );
    fieldMapping.spot_defineAttribute("mimeType",null);
    fieldMapping.spot_defineAttribute("delimiter",null);
    spot_addElement( "replaceTableColumnTitle", replaceTableColumnTitle );
    spot_addElement( "replaceTableColumns", replaceTableColumns );
    replaceTableColumns.spot_defineAttribute("columnCount",null);
    spot_addElement( "projectWidgetAsCollection", projectWidgetAsCollection );
    projectWidgetAsCollection.spot_defineAttribute("name",null);
    projectWidgetAsCollection.spot_defineAttribute("title",null);
    projectWidgetAsCollection.spot_defineAttribute("registerSelectionView",null);
    projectWidgetAsCollection.spot_defineAttribute("useWidgetAsSelectionSource",null);
    projectWidgetAsCollection.spot_defineAttribute("selectionViewTitle",null);
    spot_addElement( "itemAttributeHandling", itemAttributeHandling );
    spot_addElement( "updateWhenDataChanges", updateWhenDataChanges );
    spot_addElement( "copySourceViews", copySourceViews );
    spot_addElement( "views", views );
    spot_addElement( "initialSelection", initialSelection );
    initialSelection.spot_defineAttribute("selectionType","index");
    spot_addElement( "generateCategoryViews", generateCategoryViews );
    generateCategoryViews.spot_defineAttribute("categoryColumn",null);
    generateCategoryViews.spot_defineAttribute("useLinkedDataWhenGrouping",null);
    generateCategoryViews.spot_defineAttribute("register",null);
    generateCategoryViews.spot_defineAttribute("typeMask",null);
    spot_addElement( "grouping", grouping );
  }

  /**
   * Gets the views element
   * 
   * @return the views element or null if a reference was never created
   */
  public SPOTSet getViews() { return views; }

  /**
   * Gets the reference to the views element
   * A reference is created if necessary
   * 
   * @return the reference to the views element
   */
  public SPOTSet getViewsReference() {
    if ( views == null ) {
      views = new SPOTSet( "view", new DataView(), -1, -1, true);
      super.spot_setReference( "views" , views);
    }
    return views;
  }

  /**
   * Sets the reference to the views element
   * @param reference the reference ( can be null)
   * 
   * @throws ClassCastException if the parameter is not valid
   */
  public void setViews(iSPOTElement reference) throws ClassCastException {
    views = (SPOTSet)reference;
    spot_setReference( "views" ,reference);
  }

  /**
   * Gets the grouping element
   * 
   * @return the grouping element or null if a reference was never created
   */
  public GroupingInfo getGrouping() { return grouping; }

  /**
   * Gets the reference to the grouping element
   * A reference is created if necessary
   * 
   * @return the reference to the grouping element
   */
  public GroupingInfo getGroupingReference() {
    if ( grouping == null ) {
      grouping = new GroupingInfo(true);
      super.spot_setReference( "grouping" , grouping);
      grouping.spot_defineAttribute("appendCounts",null);
      grouping.spot_defineAttribute("boldGroupTitles",null);
      grouping.spot_defineAttribute("titlesSelectable",null);
    }
    return grouping;
  }

  /**
   * Sets the reference to the grouping element
   * @param reference the reference ( can be null)
   * 
   * @throws ClassCastException if the parameter is not valid
   */
  public void setGrouping(iSPOTElement reference) throws ClassCastException {
    grouping = (GroupingInfo)reference;
    spot_setReference( "grouping" ,reference);
  }

  //}GENERATED_METHODS

  //GENERATED_INNER_CLASSES{

  /**
   * Class that defines the valid set of choices for
   * the <code>CollectionTarget.itemAttributeHandling</code> ENUMERATED object
   */
  public static class CItemAttributeHandling extends SPOTEnumerated {

    /** pass the item to the widget */
    public final static int none = 0;
    /** extract the attributes and apply then to the widget */
    public final static int apply_to_widget = 1;
    public final static int convert_to_html = 2;
    /** strip t */
    public final static int strip = 3;
    /**
     * Creates a new <code>CItemAttributeHandling</code> object
     */
    public CItemAttributeHandling()
    {
      this(null,null,null,null,true);
    }

    /**
     * Creates a new <code>CItemAttributeHandling</code> object
     * 
     * @param val the value
     */
    public CItemAttributeHandling( int val )
    {
      super();
      _sChoices=_schoices;
      _nChoices=_nchoices;
      setValue(val);
    }

    /**
     * Creates a new <code>itemAttributeHandling</code> object
     * the <code>CollectionTarget.itemAttributeHandling</code> ENUMERATED object
     * 
     * @param ival         the integer value
     * @param sval         the string  value
     * @param idefaultval  the integer default value
     * @param sdefaultval  the string default value
     * @param optional   <code>true</code> if the node the object represents is optional
     */
    public CItemAttributeHandling( Integer ival, String sval, Integer idefaultval, String sdefaultval, boolean optional)
    {
      super(ival,sval,idefaultval,sdefaultval,optional);
      _sChoices=_schoices;
      _nChoices=_nchoices;
    }

    /**
     * Retrieves the range of valid values for the object
     * 
     * @return the valid range as a displayable string
     */
    public String spot_getValidityRange()
    {
      return "{"
      +"none(0), "
      +"apply_to_widget(1), "
      +"convert_to_html(2), "
      +"strip(3) }";
    }
    private final static int    _nchoices[] = {
              0,
              1,
              2,
              3
             };


    private final static String _schoices[] = {
              "none",
              "apply_to_widget",
              "convert_to_html",
              "strip"
             };

  }
  //}GENERATED_INNER_CLASSES
}
