/**************************************************************************
 * DataCollection.java - Mon Sep 12 15:39:20 PDT 2022
 *
 * Copyright (c) SparseWare Inc
 *
 * All rights reserved.
 *
 * Generated by the Sparse Notation(tm) To Java Compiler v1.0
 * Note 1: Code entered after the "//USER_IMPORTS_AND_COMMENTS_MARK{}" comment and before the class declaration will be preserved.
 * Note 2: Code entered out side of the other   comment blocks will be preserved
 * Note 3: If you edit the automatically generated comments and want to preserve your edits remove the //GENERATED_COMMENT{} tags
 */

package com.appnativa.datacollection.spot;

import com.appnativa.spot.*;

//USER_IMPORTS_AND_COMMENTS_MARK{}


//GENERATED_COMMENT{}
/**
 * This class represents a data collection. The data is
 * retrieved via the dataURL.
 * <p>
 * The option selection filter is then applied to filter the
 * results
 * </p>
 *
 * @author Don DeCoteau
 * @version 1.0
 */  
public class DataCollection extends SPOTSequence {
  //GENERATED_MEMBERS{

//GENERATED_COMMENT{}
  /** the name of the collection */ 
  public SPOTPrintableString name = new SPOTPrintableString(null, 0, 64, false);

//GENERATED_COMMENT{}
  /** the name of the collection */ 
  public SPOTPrintableString title = new SPOTPrintableString(null, 0, 64, true);

//GENERATED_COMMENT{}
  /** the description of the item */ 
  public SPOTPrintableString description = new SPOTPrintableString(null, 0, 255, true);

//GENERATED_COMMENT{}
  /** Appearance~icon~reload: url to use to retrieve an icon associated with the value (if not defined, the icon of the widget is used) */ 
  public SPOTPrintableString icon = new SPOTPrintableString(null, 0, 255, true);

//GENERATED_COMMENT{}
  /** Design~url: the URL for a script that handles the collection's events */ 
  public SPOTPrintableString eventHandlerURL = new SPOTPrintableString();

//GENERATED_COMMENT{}
  /** the name of class that handles the collection. If not specified the default handler is used */ 
  public SPOTPrintableString handler = new SPOTPrintableString(null, 0, 255, true);

//GENERATED_COMMENT{}
  /** a URL to use to retrieve data for the collection or collection definition can be a collection: URL */ 
  public SPOTPrintableString dataURL = new SPOTPrintableString();

//GENERATED_COMMENT{}
  /** whether the data is blob (blobs automatically have href,mime_tye,value columns defined) */ 
  public SPOTBoolean blob = new SPOTBoolean(null, false, false );

//GENERATED_COMMENT{}
  /** whether the collection can be graphed; if not set the data column value types are used to figure this out */ 
  public SPOTBoolean graphable = new SPOTBoolean();

  protected SPOTSet columns = null;

//GENERATED_COMMENT{}
  /** set of parameters that can be applied to the data url to restrict the results set */ 
  protected SPOTSet queryParameters = null;

//GENERATED_COMMENT{}
  /** whether the collection is sorted after it is loaded */ 
  public SPOTBoolean sort = new SPOTBoolean(null, false, false );

//GENERATED_COMMENT{}
  /** the name of the column that is a unique key correlating to a name type column (if no specified the linked data in a name_linked_id type column is assumed) */ 
  public SPOTPrintableString uniqueKeyColumnName = new SPOTPrintableString(null, 0, 64, true);

//GENERATED_COMMENT{}
  /** Design~url: filter to use to filter the results after parsing; can be a javascript function or java class name */ 
  public SPOTPrintableString parsingFilterURL = new SPOTPrintableString();

//GENERATED_COMMENT{}
  /** Design~url: filter to use to filter the results after processing (string values converted to native types) ; can be a javascript function or java class name */ 
  public SPOTPrintableString processingFilterURL = new SPOTPrintableString();

//GENERATED_COMMENT{}
  /** Design~url: used to transform the collection after all rows have been processed; can be a javascript function java class name or SQL */ 
  public SPOTPrintableString transformURL = new SPOTPrintableString();

//GENERATED_COMMENT{}
  /** Design~url: used to transform the collection for visual presentation; can be a javascript function java class name or SQL */ 
  public SPOTPrintableString presentationTransformURL = new SPOTPrintableString();

//GENERATED_COMMENT{}
  /** Design~url: a set of custom name/value for the object. The default format is a set of name/value pairs separated by a semi-colon */ 
  public SPOTPrintableString customPropertiesURL = new SPOTPrintableString();

//GENERATED_COMMENT{}
  /** Design: whether views are registered by default */ 
  public SPOTBoolean registerViewsByDefault = new SPOTBoolean(null, false, false );

//GENERATED_COMMENT{}
  /** Design: whether the collection is registered */ 
  public SPOTBoolean registerViewsList = new SPOTBoolean(null, false, false );

//GENERATED_COMMENT{}
  /** the message to display when the collection is empty */ 
  public SPOTPrintableString noDataMessage = new SPOTPrintableString();

//GENERATED_COMMENT{}
  /** predefined views for this collection */ 
  protected SPOTSet views = null;

  //}GENERATED_MEMBERS

  //GENERATED_METHODS{

  /**
   * Creates a new optional <code>DataCollection</code> object.
   */
  public DataCollection()  {
    this(true);
  }

  /**
   * Creates a new <code>DataCollection</code> object.
   *
   * @param optional  <code>true</code> if the element is optional; <code>false</code> otherwise)
   */
  public DataCollection( boolean optional ) {
    super( optional, false );
    spot_setElements();
  }

  /**
   * Creates a new <code>DataCollection</code> object.
   *
   * @param optional  <code>true</code> if the element is optional; <code>false</code> otherwise)
   * @param setElements  <code>true</code> if a call to setElements should be made; <code>false</code> otherwise)
   */
  protected DataCollection( boolean optional,boolean setElements ) {
    super( optional, setElements );
  }

  /**
   * Adds elements to the object elements map
   *
   */
  protected void spot_setElements()  {
    this.elementsSizeHint  +=22;
    this.attributeSizeHint +=4;
    super.spot_setElements();
    spot_defineAttribute("onCreated",null);
    spot_defineAttribute("onDispose",null);
    spot_defineAttribute("onStartedLoading",null);
    spot_defineAttribute("onFinishedLoading",null);
    spot_addElement( "name", name );
    spot_addElement( "title", title );
    spot_addElement( "description", description );
    spot_addElement( "icon", icon );
    icon.spot_defineAttribute("alt",null);
    icon.spot_defineAttribute("slice",null);
    icon.spot_defineAttribute("size",null);
    icon.spot_defineAttribute("scaling",null);
    icon.spot_defineAttribute("density",null);
    spot_addElement( "eventHandlerURL", eventHandlerURL );
    eventHandlerURL.spot_defineAttribute("mimeType",null);
    eventHandlerURL.spot_defineAttribute("inline",null);
    spot_addElement( "handler", handler );
    spot_addElement( "dataURL", dataURL );
    dataURL.spot_defineAttribute("mimeType",null);
    dataURL.spot_defineAttribute("method",null);
    dataURL.spot_defineAttribute("deferred",null);
    dataURL.spot_defineAttribute("columnSeparator",null);
    dataURL.spot_defineAttribute("inline",null);
    dataURL.spot_defineAttribute("ldSeparator",null);
    dataURL.spot_defineAttribute("riSeparator",null);
    dataURL.spot_defineAttribute("unescape","false");
    dataURL.spot_defineAttribute("parser",null);
    dataURL.spot_defineAttribute("customProperties",null);
    dataURL.spot_defineAttribute("linkAttributes",null);
    dataURL.spot_defineAttribute("copyType",null);
    spot_addElement( "blob", blob );
    spot_addElement( "graphable", graphable );
    spot_addElement( "columns", columns );
    spot_addElement( "queryParameters", queryParameters );
    spot_addElement( "sort", sort );
    sort.spot_defineAttribute("column",null);
    sort.spot_defineAttribute("descending",null);
    sort.spot_defineAttribute("loadSortColumn",null);
    sort.spot_defineAttribute("loadSortDescending",null);
    sort.spot_defineAttribute("caseInsensitive",null);
    spot_addElement( "uniqueKeyColumnName", uniqueKeyColumnName );
    uniqueKeyColumnName.spot_defineAttribute("useLinkedData",null);
    spot_addElement( "parsingFilterURL", parsingFilterURL );
    parsingFilterURL.spot_defineAttribute("mimeType",null);
    parsingFilterURL.spot_defineAttribute("inline",null);
    spot_addElement( "processingFilterURL", processingFilterURL );
    processingFilterURL.spot_defineAttribute("mimeType",null);
    processingFilterURL.spot_defineAttribute("inline",null);
    spot_addElement( "transformURL", transformURL );
    transformURL.spot_defineAttribute("mimeType",null);
    transformURL.spot_defineAttribute("inline",null);
    spot_addElement( "presentationTransformURL", presentationTransformURL );
    presentationTransformURL.spot_defineAttribute("mimeType",null);
    presentationTransformURL.spot_defineAttribute("inline",null);
    spot_addElement( "customPropertiesURL", customPropertiesURL );
    customPropertiesURL.spot_defineAttribute("mimeType",null);
    customPropertiesURL.spot_defineAttribute("delimiter",null);
    customPropertiesURL.spot_defineAttribute("inline",null);
    spot_addElement( "registerViewsByDefault", registerViewsByDefault );
    spot_addElement( "registerViewsList", registerViewsList );
    registerViewsList.spot_defineAttribute("name",null);
    registerViewsList.spot_defineAttribute("title",null);
    registerViewsList.spot_defineAttribute("description",null);
    registerViewsList.spot_defineAttribute("addParent","true");
    registerViewsList.spot_defineAttribute("parentTitle","All");
    spot_addElement( "noDataMessage", noDataMessage );
    noDataMessage.spot_defineAttribute("isResource",null);
    spot_addElement( "views", views );
  }

  /**
   * Gets the columns element
   * 
   * @return the columns element or null if a reference was never created
   */
  public SPOTSet getColumns() { return columns; }

  /**
   * Gets the reference to the columns element
   * A reference is created if necessary
   * 
   * @return the reference to the columns element
   */
  public SPOTSet getColumnsReference() {
    if ( columns == null ) {
      columns = new SPOTSet( "column", new DataColumn(), -1, -1, true);
      super.spot_setReference( "columns" , columns);
    }
    return columns;
  }

  /**
   * Sets the reference to the columns element
   * @param reference the reference ( can be null)
   * 
   * @throws ClassCastException if the parameter is not valid
   */
  public void setColumns(iSPOTElement reference) throws ClassCastException {
    columns = (SPOTSet)reference;
    spot_setReference( "columns" ,reference);
  }

  /**
   * Gets the queryParameters element
   * 
   * @return the queryParameters element or null if a reference was never created
   */
  public SPOTSet getQueryParameters() { return queryParameters; }

  /**
   * Gets the reference to the queryParameters element
   * A reference is created if necessary
   * 
   * @return the reference to the queryParameters element
   */
  public SPOTSet getQueryParametersReference() {
    if ( queryParameters == null ) {
      queryParameters = new SPOTSet( "column", new DataColumn(), -1, -1, true);
      super.spot_setReference( "queryParameters" , queryParameters);
      queryParameters.spot_defineAttribute("required",null);
    }
    return queryParameters;
  }

  /**
   * Sets the reference to the queryParameters element
   * @param reference the reference ( can be null)
   * 
   * @throws ClassCastException if the parameter is not valid
   */
  public void setQueryParameters(iSPOTElement reference) throws ClassCastException {
    queryParameters = (SPOTSet)reference;
    spot_setReference( "queryParameters" ,reference);
  }

  /**
   * Gets the views element
   * 
   * @return the views element or null if a reference was never created
   */
  public SPOTSet getViews() { return views; }

  /**
   * Gets the reference to the views element
   * A reference is created if necessary
   * 
   * @return the reference to the views element
   */
  public SPOTSet getViewsReference() {
    if ( views == null ) {
      views = new SPOTSet( "view", new DataView(), -1, -1, true);
      super.spot_setReference( "views" , views);
    }
    return views;
  }

  /**
   * Sets the reference to the views element
   * @param reference the reference ( can be null)
   * 
   * @throws ClassCastException if the parameter is not valid
   */
  public void setViews(iSPOTElement reference) throws ClassCastException {
    views = (SPOTSet)reference;
    spot_setReference( "views" ,reference);
  }

  //}GENERATED_METHODS
  java.util.Map<String,DataView> mappedViews;
  public  DataView getView(String name) {
    if(mappedViews==null && views!=null) {
      mappedViews=new java.util.HashMap<>(views.size());
      for(DataView dv:(java.util.List<DataView>)views.unsafeGetObjectList()) {
        mappedViews.put(dv.name.getValue(),dv);
      }
    }
    return mappedViews==null ? null : mappedViews.get(name);
  }
  public DataCollection getRawValuesCopy() {
    DataCollection dc   = (DataCollection) this.clone();
    SPOTSet        list = dc.getColumns();
    if (list == null) {
      return dc;
    }
    createRawColumns(list.unsafeGetObjectList());
    dc.parsingFilterURL.setValue((String) null);
    dc.transformURL.setValue((String) null);
    dc.processingFilterURL.setValue((String) null);
    dc.presentationTransformURL.setValue((String) null);
    return dc;
  }

  protected void createRawColumns(java.util.List<DataColumn> list) {
    for (DataColumn col : list) {
      col.valueType.setValue(DataColumn.CValueType.string_type);
      col.valueContext.setValue((String) null);
      if (col.getStructColumns() != null) {
        createRawColumns(col.getStructColumns().unsafeGetObjectList());
      }
    }

  }
  //GENERATED_INNER_CLASSES{

  //}GENERATED_INNER_CLASSES
}
