/**************************************************************************
 * DataColumn.java - Mon Sep 12 15:39:20 PDT 2022
 *
 * Copyright (c) SparseWare Inc
 *
 * All rights reserved.
 *
 * Generated by the Sparse Notation(tm) To Java Compiler v1.0
 * Note 1: Code entered after the "//USER_IMPORTS_AND_COMMENTS_MARK{}" comment and before the class declaration will be preserved.
 * Note 2: Code entered out side of the other   comment blocks will be preserved
 * Note 3: If you edit the automatically generated comments and want to preserve your edits remove the //GENERATED_COMMENT{} tags
 */

package com.appnativa.datacollection.spot;

import com.appnativa.spot.*;

//USER_IMPORTS_AND_COMMENTS_MARK{}

public class DataColumn extends SPOTSequence {
  //GENERATED_MEMBERS{

//GENERATED_COMMENT{}
  /** the name to use to reference the item */ 
  public SPOTPrintableString name = new SPOTPrintableString(null, 0, 64, false);

//GENERATED_COMMENT{}
  /** the name of the collection */ 
  public SPOTPrintableString title = new SPOTPrintableString(null, 0, 64, true);

//GENERATED_COMMENT{}
  /** the description of the item */ 
  public SPOTPrintableString description = new SPOTPrintableString(null, 0, 255, true);

//GENERATED_COMMENT{}
  /** Design: the type of data the column represents */ 
  public CValueType valueType = new CValueType(null, null, CValueType.string_type, "string_type", false );

  public CColumnType columnType = new CColumnType(null, null, CColumnType.other, "other", false );

//GENERATED_COMMENT{}
  /** index into the source collection's array (if specified, it must be specified for all columns) */ 
  public SPOTInteger dataIndex = new SPOTInteger(null, -1, false );

//GENERATED_COMMENT{}
  /** Design~class: the class name for the converter to convert to and from the type */ 
  public SPOTPrintableString converterClass = new SPOTPrintableString();

//GENERATED_COMMENT{}
  /** Design~class: the class name for the converter to convert to and from the type */ 
  public SPOTPrintableString linkedDataConverterClass = new SPOTPrintableString();

//GENERATED_COMMENT{}
  /** additional value describing a value (e.g. date format for dates) */ 
  public SPOTPrintableString valueContext = new SPOTPrintableString();

//GENERATED_COMMENT{}
  /** additional value describing the linked data */ 
  public SPOTPrintableString linkedDataContext = new SPOTPrintableString();

//GENERATED_COMMENT{}
  /** true if this column is created and inserted into the data stream at runtime */ 
  public SPOTBoolean runtime = new SPOTBoolean(null, false, false );

  protected SPOTSet structColumns = null;

  //}GENERATED_MEMBERS

  //GENERATED_METHODS{

  /**
   * Creates a new optional <code>DataColumn</code> object.
   */
  public DataColumn()  {
    this(true);
  }

  /**
   * Creates a new <code>DataColumn</code> object.
   *
   * @param optional  <code>true</code> if the element is optional; <code>false</code> otherwise)
   */
  public DataColumn( boolean optional ) {
    super( optional, false );
    spot_setElements();
  }

  /**
   * Creates a new <code>DataColumn</code> object.
   *
   * @param optional  <code>true</code> if the element is optional; <code>false</code> otherwise)
   * @param setElements  <code>true</code> if a call to setElements should be made; <code>false</code> otherwise)
   */
  protected DataColumn( boolean optional,boolean setElements ) {
    super( optional, setElements );
  }

  /**
   * Adds elements to the object elements map
   *
   */
  protected void spot_setElements()  {
    this.elementsSizeHint  +=12;
    super.spot_setElements();
    spot_addElement( "name", name );
    spot_addElement( "title", title );
    spot_addElement( "description", description );
    spot_addElement( "valueType", valueType );
    valueType.spot_defineAttribute("raw","false");
    spot_addElement( "columnType", columnType );
    spot_addElement( "dataIndex", dataIndex );
    spot_addElement( "converterClass", converterClass );
    spot_addElement( "linkedDataConverterClass", linkedDataConverterClass );
    spot_addElement( "valueContext", valueContext );
    spot_addElement( "linkedDataContext", linkedDataContext );
    spot_addElement( "runtime", runtime );
    runtime.spot_defineAttribute("isTemplate","false");
    spot_addElement( "structColumns", structColumns );
  }

  /**
   * Gets the structColumns element
   * 
   * @return the structColumns element or null if a reference was never created
   */
  public SPOTSet getStructColumns() { return structColumns; }

  /**
   * Gets the reference to the structColumns element
   * A reference is created if necessary
   * 
   * @return the reference to the structColumns element
   */
  public SPOTSet getStructColumnsReference() {
    if ( structColumns == null ) {
      structColumns = new SPOTSet( "column", new DataColumn(), -1, -1, true);
      super.spot_setReference( "structColumns" , structColumns);
      structColumns.spot_defineAttribute("templateName",null);
      structColumns.spot_defineAttribute("addTemplateColumnsAfter","false");
    }
    return structColumns;
  }

  /**
   * Sets the reference to the structColumns element
   * @param reference the reference ( can be null)
   * 
   * @throws ClassCastException if the parameter is not valid
   */
  public void setStructColumns(iSPOTElement reference) throws ClassCastException {
    structColumns = (SPOTSet)reference;
    spot_setReference( "structColumns" ,reference);
  }

  //}GENERATED_METHODS

  //GENERATED_INNER_CLASSES{

  /**
   * Class that defines the valid set of choices for
   * the <code>DataColumn.valueType</code> ENUMERATED object
   */
  public static class CValueType extends SPOTEnumerated {

    /** the data represents string items */
    public final static int string_type = 1;
    /** the data represents integer numbers */
    public final static int integer_type = 2;
    /** the data represents decimal numbers */
    public final static int decimal_type = 3;
    /** the data represents date and time items */
    public final static int date_time_type = 4;
    /** the data represents date items */
    public final static int date_type = 5;
    /** the data represents time items */
    public final static int time_type = 6;
    /** the data represents boolean items */
    public final static int boolean_type = 7;
    /** the data represents a byte array that will be base64 encoded */
    public final static int bytes_base64_type = 8;
    /** the data represents items that themselves can contain other items  (valueContext equivalent to mime type separator attributes for dataURL for CSV data) */
    public final static int struct_type = 9;
    /** the data represents array items  (valueContext equivalent to mime type separator attributes for dataURL for CSV data) */
    public final static int array_type = 10;
    /** the data represents number range */
    public final static int number_range_type = 11;
    /** item represent an enumeration */
    public final static int enum_type = 12;
    /** the data represents widget items */
    public final static int widget_type = 98;
    /** items are of a custom type */
    public final static int custom_type = 99;
    /**
     * Creates a new <code>CValueType</code> object
     */
    public CValueType()
    {
      this(null,null,null,null,true);
    }

    /**
     * Creates a new <code>CValueType</code> object
     * 
     * @param val the value
     */
    public CValueType( int val )
    {
      super();
      _sChoices=_schoices;
      _nChoices=_nchoices;
      spot_setAttributes();
      setValue(val);
    }

    /**
     * Creates a new <code>valueType</code> object
     * the <code>DataColumn.valueType</code> ENUMERATED object
     * 
     * @param ival         the integer value
     * @param sval         the string  value
     * @param idefaultval  the integer default value
     * @param sdefaultval  the string default value
     * @param optional   <code>true</code> if the node the object represents is optional
     */
    public CValueType( Integer ival, String sval, Integer idefaultval, String sdefaultval, boolean optional)
    {
      super(ival,sval,idefaultval,sdefaultval,optional);
      _sChoices=_schoices;
      _nChoices=_nchoices;
      spot_setAttributes();
    }

    /**
     * Retrieves the range of valid values for the object
     * 
     * @return the valid range as a displayable string
     */
    public String spot_getValidityRange()
    {
      return "{"
      +"string_type(1), "
      +"integer_type(2), "
      +"decimal_type(3), "
      +"date_time_type(4), "
      +"date_type(5), "
      +"time_type(6), "
      +"boolean_type(7), "
      +"bytes_base64_type(8), "
      +"struct_type(9), "
      +"array_type(10), "
      +"number_range_type(11), "
      +"enum_type(12), "
      +"widget_type(98), "
      +"custom_type(99) }";
    }

    private void spot_setAttributes()
    {
      this.attributeSizeHint +=1;
      spot_defineAttribute("raw","false");
    }
    private final static int    _nchoices[] = {
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              98,
              99
             };


    private final static String _schoices[] = {
              "string_type",
              "integer_type",
              "decimal_type",
              "date_time_type",
              "date_type",
              "time_type",
              "boolean_type",
              "bytes_base64_type",
              "struct_type",
              "array_type",
              "number_range_type",
              "enum_type",
              "widget_type",
              "custom_type"
             };

  }
  /**
   * Class that defines the valid set of choices for
   * the <code>DataColumn.columnType</code> ENUMERATED object
   */
  public static class CColumnType extends SPOTEnumerated {

    /** unspecified column type */
    public final static int other = 0;
    /** the id that uniquely identifies the record within its domain */
    public final static int id = 1;
    /** timestamp for the value, this is inherently a domain value */
    public final static int timestamp = 2;
    /** the name of the represented entity */
    public final static int name = 3;
    /** the name and a linked id that uniquely identifies the entity within its domain */
    public final static int name_linked_id = 4;
    /** a value that can be used as a domain for graphing */
    public final static int domain = 5;
    /** the value associated with the name */
    public final static int value = 6;
    /** represents the units for the value column */
    public final static int value_units = 7;
    /** represents the valid range for values */
    public final static int value_range = 8;
    /** a description of the represented entity */
    public final static int description = 9;
    /** the mime type for the value */
    public final static int mime_type = 10;
    /** the string representation of the url used to retrieve the value */
    public final static int href = 11;
    /** the string representation of the url used to retrieve the value */
    public final static int hidden = 12;
    /** // the linked data is id that uniquely identifies the record within its domain */
    public final static int linked_id = 13;
    /** // the linked data is id that uniquely identifies the record within its domain */
    public final static int domain_linked_id = 14;
    /** // the linked data is id that uniquely identifies the record within its domain */
    public final static int timestamp_linked_id = 15;
    /** item represents a category designation */
    public final static int category = 16;
    /**
     * Creates a new <code>CColumnType</code> object
     */
    public CColumnType()
    {
      this(null,null,null,null,true);
    }

    /**
     * Creates a new <code>CColumnType</code> object
     * 
     * @param val the value
     */
    public CColumnType( int val )
    {
      super();
      _sChoices=_schoices;
      _nChoices=_nchoices;
      setValue(val);
    }

    /**
     * Creates a new <code>columnType</code> object
     * the <code>DataColumn.columnType</code> ENUMERATED object
     * 
     * @param ival         the integer value
     * @param sval         the string  value
     * @param idefaultval  the integer default value
     * @param sdefaultval  the string default value
     * @param optional   <code>true</code> if the node the object represents is optional
     */
    public CColumnType( Integer ival, String sval, Integer idefaultval, String sdefaultval, boolean optional)
    {
      super(ival,sval,idefaultval,sdefaultval,optional);
      _sChoices=_schoices;
      _nChoices=_nchoices;
    }

    /**
     * Retrieves the range of valid values for the object
     * 
     * @return the valid range as a displayable string
     */
    public String spot_getValidityRange()
    {
      return "{"
      +"other(0), "
      +"id(1), "
      +"timestamp(2), "
      +"name(3), "
      +"name_linked_id(4), "
      +"domain(5), "
      +"value(6), "
      +"value_units(7), "
      +"value_range(8), "
      +"description(9), "
      +"mime_type(10), "
      +"href(11), "
      +"hidden(12), "
      +"linked_id(13), "
      +"domain_linked_id(14), "
      +"timestamp_linked_id(15), "
      +"category(16) }";
    }
    private final static int    _nchoices[] = {
              0,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16
             };


    private final static String _schoices[] = {
              "other",
              "id",
              "timestamp",
              "name",
              "name_linked_id",
              "domain",
              "value",
              "value_units",
              "value_range",
              "description",
              "mime_type",
              "href",
              "hidden",
              "linked_id",
              "domain_linked_id",
              "timestamp_linked_id",
              "category"
             };

  }
  //}GENERATED_INNER_CLASSES
}
