/**************************************************************************
 * GroupingInfo.java - Mon Sep 12 15:39:20 PDT 2022
 *
 * Copyright (c) SparseWare Inc
 *
 * All rights reserved.
 *
 * Generated by the Sparse Notation(tm) To Java Compiler v1.0
 * Note 1: Code entered after the "//USER_IMPORTS_AND_COMMENTS_MARK{}" comment and before the class declaration will be preserved.
 * Note 2: Code entered out side of the other   comment blocks will be preserved
 * Note 3: If you edit the automatically generated comments and want to preserve your edits remove the //GENERATED_COMMENT{} tags
 */

package com.appnativa.datacollection.spot;

import com.appnativa.spot.*;

//USER_IMPORTS_AND_COMMENTS_MARK{}

public class GroupingInfo extends SPOTSequence {
  //GENERATED_MEMBERS{

//GENERATED_COMMENT{}
  /** columns to group the collection by (names or numbers) */ 
  public SPOTPrintableString columns = new SPOTPrintableString();

//GENERATED_COMMENT{}
  /** the location where the group title with be placed if grouping tabular data */ 
  public SPOTInteger groupTitleColumnPosition = new SPOTInteger(null, 1, false );

//GENERATED_COMMENT{}
  /** whether grouping columns will be preserved once grouping has occurred */ 
  public SPOTBoolean preserveGroupingColumns = new SPOTBoolean(null, true, false );

//GENERATED_COMMENT{}
  /** whether values should be compared as string when grouping */ 
  public SPOTBoolean useStringComparison = new SPOTBoolean(null, true, false );

//GENERATED_COMMENT{}
  /** comma separated list of numbers denoting the sorting order for each group (-1 = descending, 0 = not sorting, 1 = ascending) */ 
  public SPOTPrintableString groupingSortOrder = new SPOTPrintableString(null, 0, 20, true);

//GENERATED_COMMENT{}
  /** The name of number of the column to sort the items of the last grouping by */ 
  public SPOTPrintableString sortingColumn = new SPOTPrintableString(null, 0, 64, true);

  //}GENERATED_MEMBERS

  //GENERATED_METHODS{

  /**
   * Creates a new optional <code>GroupingInfo</code> object.
   */
  public GroupingInfo()  {
    this(true);
  }

  /**
   * Creates a new <code>GroupingInfo</code> object.
   *
   * @param optional  <code>true</code> if the element is optional; <code>false</code> otherwise)
   */
  public GroupingInfo( boolean optional ) {
    super( optional, false );
    spot_setElements();
  }

  /**
   * Creates a new <code>GroupingInfo</code> object.
   *
   * @param optional  <code>true</code> if the element is optional; <code>false</code> otherwise)
   * @param setElements  <code>true</code> if a call to setElements should be made; <code>false</code> otherwise)
   */
  protected GroupingInfo( boolean optional,boolean setElements ) {
    super( optional, setElements );
  }

  /**
   * Adds elements to the object elements map
   *
   */
  protected void spot_setElements()  {
    this.elementsSizeHint  +=6;
    super.spot_setElements();
    spot_addElement( "columns", columns );
    spot_addElement( "groupTitleColumnPosition", groupTitleColumnPosition );
    spot_addElement( "preserveGroupingColumns", preserveGroupingColumns );
    spot_addElement( "useStringComparison", useStringComparison );
    spot_addElement( "groupingSortOrder", groupingSortOrder );
    spot_addElement( "sortingColumn", sortingColumn );
    sortingColumn.spot_defineAttribute("sortOrder","1");
  }

  //}GENERATED_METHODS

  //GENERATED_INNER_CLASSES{

  //}GENERATED_INNER_CLASSES
}
