// Predictive Recursive Descent Parser generated by Solar 1.4.0
// Generated from SLR(1) grammar without grammar modifications!

const parserInstance = {
  lexer: null,
  tokens: [],
  pos: 0,
  la: null,

    _match(kind) {
  if (this.la.kind !== kind) {
    this._error(`Expected ${kind}, got ${this.la.kind}`);
  }
  const token = this.la;
  this._advance();
  return token.value;
  },
  
  _check(...kinds) {
  return kinds.includes(this.la.kind);
  },
  
  _canParse(typeName) {
  // Check if lookahead is in FIRST set of typeName
  // For POC, simplified check
  return true; // TODO: Implement proper FIRST set lookup
  },
  
  _advance() {
  if (this.pos >= this.tokens.length) {
    this.la = { kind: '$end', value: null };
  } else {
    const token = this.tokens[this.pos++];
    this.la = { kind: token[0], value: token[1], loc: token[2] };
  }
  },
  _error(msg) {
  throw new Error(`Parse error: ${msg}`);
  },
  
  parse(input) {
  // Set up lexer
  if (!this.lexer) {
    throw new Error('Lexer not set');
  }
  
  this.tokens = this.lexer.tokens;
  this.pos = 0;
  this._advance(); // Initialize lookahead
  
  // Parse root
  return this.parseRoot();
  },

    parseRoot() {
  switch (this.la.kind) {
      case '':
        return this._match('');
  
      case 'IDENTIFIER':
      case '@':
      case 'PARAM_START':
      case '[':
      case '{':
      case 'NUMBER':
      case 'STRING':
      case 'STRING_START':
      case 'JS':
      case 'REGEX':
      case 'REGEX_START':
      case 'UNDEFINED':
      case 'NULL':
      case 'BOOL':
      case 'INFINITY':
      case 'NAN':
      case '(':
      case 'SUPER':
      case 'DYNAMIC_IMPORT':
      case 'DO_IIFE':
      case 'THIS':
      case 'NEW_TARGET':
      case 'IMPORT_META':
      case '->':
      case '=>':
      case 'UNARY':
      case 'DO':
      case 'UNARY_MATH':
      case '-':
      case '+':
      case 'AWAIT':
      case '--':
      case '++':
      case 'TRY':
      case 'FOR':
      case 'SWITCH':
      case 'CLASS':
      case 'THROW':
      case 'YIELD':
      case 'DEF':
      case 'IF':
      case 'UNLESS':
      case 'RETURN':
      case 'STATEMENT':
      case 'IMPORT':
      case 'EXPORT':
      case 'WHILE':
      case 'UNTIL':
      case 'LOOP':
        return this.parseBody();
  
    default:
      this._error('Expected Root, got ' + this.la.kind);
  }
  },
  
  parseBody() {
  return this.parseLine();
  },
  
  parseLine() {
  return this.parseExpression();
  },
  
  parseStatement() {
  switch (this.la.kind) {
      case 'RETURN':
        return this.parseReturn();
  
      case 'STATEMENT':
        return this._match('STATEMENT');
  
      case 'IMPORT':
        return this.parseImport();
  
      case 'EXPORT':
        return this.parseExport();
  
    default:
      this._error('Expected Statement, got ' + this.la.kind);
  }
  },
  
  parseExpression() {
  return this.parseValue();
  },
  
  parseDef() {
  this._match('DEF');
    const $2 = this.parseIdentifier();
    this._match('CALL_START');
    const $4 = this.parseParamList();
    this._match('CALL_END');
    const $6 = this.parseBlock();
  return items;
  },
  
  parseExpressionLine() {
  switch (this.la.kind) {
      case 'PARAM_START':
      case '->':
      case '=>':
        return this.parseCodeLine();
  
      case 'UNARY':
      case 'DO':
      case 'DO_IIFE':
        return this.parseOperationLine();
  
    default:
      this._error('Expected ExpressionLine, got ' + this.la.kind);
  }
  },
  
  parseYield() {
  return this.parseYIELD();
  },
  
  parseBlock() {
  this._match('INDENT');
    this._match('OUTDENT');
  return items;
  },
  
  parseIdentifier() {
  this._match('IDENTIFIER');
  return items;
  },
  
  parseProperty() {
  this._match('PROPERTY');
  return items;
  },
  
  parseAlphaNumeric() {
  switch (this.la.kind) {
      case 'NUMBER':
        return this._match('NUMBER');
  
      case 'STRING':
      case 'STRING_START':
        return this.parseString();
  
    default:
      this._error('Expected AlphaNumeric, got ' + this.la.kind);
  }
  },
  
  parseString() {
  switch (this.la.kind) {
      case 'STRING':
        return this._match('STRING');
  
      case 'STRING_START':
        { this._match('STRING_START'); const _1_2 = this.parseInterpolations(); this._match('STRING_END'); return items; }
  
    default:
      this._error('Expected String, got ' + this.la.kind);
  }
  },
  
  parseInterpolations() {
  const items = [this.parseInterpolationChunk()];
  
  while (this._canParse('InterpolationChunk')) {
    items.push(this.parseInterpolationChunk());
  }
  
  return items;
  },
  
  parseInterpolationChunk() {
  this._match('INTERPOLATION_START');
    const $2 = this.parseBody();
    this._match('INTERPOLATION_END');
  return items;
  },
  
  parseRegex() {
  switch (this.la.kind) {
      case 'REGEX':
        return this._match('REGEX');
  
      case 'REGEX_START':
        { this._match('REGEX_START'); const _1_2 = this.parseInvocation(); this._match('REGEX_END'); return items; }
  
    default:
      this._error('Expected Regex, got ' + this.la.kind);
  }
  },
  
  parseRegexWithIndex() {
  const $1 = this.parseRegex();
    this._match(',');
    const $3 = this.parseExpression();
  return items;
  },
  
  parseLiteral() {
  switch (this.la.kind) {
      case 'NUMBER':
      case 'STRING':
      case 'STRING_START':
        return this.parseAlphaNumeric();
  
      case 'JS':
        return this._match('JS');
  
      case 'REGEX':
      case 'REGEX_START':
        return this.parseRegex();
  
      case 'UNDEFINED':
        return this._match('UNDEFINED');
  
      case 'NULL':
        return this._match('NULL');
  
      case 'BOOL':
        return this._match('BOOL');
  
      case 'INFINITY':
        return this._match('INFINITY');
  
      case 'NAN':
        return this._match('NAN');
  
    default:
      this._error('Expected Literal, got ' + this.la.kind);
  }
  },
  
  parseAssign() {
  const $1 = this.parseAssignable();
    this._match('=');
    const $3 = this.parseExpression();
  return items;
  },
  
  parseAssignObj() {
  return this.parseObjAssignable();
  },
  
  parseSimpleObjAssignable() {
  switch (this.la.kind) {
      case 'IDENTIFIER':
        return this.parseIdentifier();
  
      case 'PROPERTY':
        return this.parseProperty();
  
      case '@':
        return this.parseThisProperty();
  
    default:
      this._error('Expected SimpleObjAssignable, got ' + this.la.kind);
  }
  },
  
  parseObjAssignable() {
  return this.parseSimpleObjAssignable();
  },
  
  parseObjRestValue() {
  this._match('...');
    const $2 = this.parseSimpleObjAssignable();
  return items;
  },
  
  parseObjSpreadExpr() {
  return this.parseSimpleObjAssignable();
  },
  
  parseReturn() {
  this._match('RETURN');
    const $2 = this.parseExpression();
  return items;
  },
  
  parseCode() {
  switch (this.la.kind) {
      case 'PARAM_START':
        { this._match('PARAM_START'); const _0_2 = this.parseParamList(); this._match('PARAM_END'); const _0_4 = this.parseFuncGlyph(); const _0_5 = this.parseBlock(); return items; }
  
      case '->':
      case '=>':
        { const _1_1 = this.parseFuncGlyph(); const _1_2 = this.parseBlock(); return items; }
  
    default:
      this._error('Expected Code, got ' + this.la.kind);
  }
  },
  
  parseCodeLine() {
  switch (this.la.kind) {
      case 'PARAM_START':
        { this._match('PARAM_START'); const _0_2 = this.parseParamList(); this._match('PARAM_END'); const _0_4 = this.parseFuncGlyph(); const _0_5 = this.parseLine(); return items; }
  
      case '->':
      case '=>':
        { const _1_1 = this.parseFuncGlyph(); const _1_2 = this.parseLine(); return items; }
  
    default:
      this._error('Expected CodeLine, got ' + this.la.kind);
  }
  },
  
  parseFuncGlyph() {
  switch (this.la.kind) {
      case '->':
        return this._match('->');
  
      case '=>':
        return this._match('=>');
  
    default:
      this._error('Expected FuncGlyph, got ' + this.la.kind);
  }
  },
  
  parseOptComma() {
  switch (this.la.kind) {
      case '':
        return this._match('');
  
      case ',':
        return this._match(',');
  
    default:
      this._error('Expected OptComma, got ' + this.la.kind);
  }
  },
  
  parseParamList() {
  return this.parse();
  },
  
  parseParam() {
  return this.parseParamVar();
  },
  
  parseParamVar() {
  switch (this.la.kind) {
      case 'IDENTIFIER':
        return this.parseIdentifier();
  
      case '@':
        return this.parseThisProperty();
  
      case '[':
        return this.parseArray();
  
      case '{':
        return this.parseObject();
  
    default:
      this._error('Expected ParamVar, got ' + this.la.kind);
  }
  },
  
  parseSplat() {
  this._match('...');
    const $2 = this.parseExpression();
  return items;
  },
  
  parseSimpleAssignable() {
  return this.parseIdentifier();
  },
  
  parseAssignable() {
  return this.parseSimpleAssignable();
  },
  
  parseValue() {
  return this.parseAssignable();
  },
  
  parseSuper() {
  this._match('SUPER');
    this._match('.');
    const $3 = this.parseProperty();
  return items;
  },
  
  parseMetaProperty() {
  switch (this.la.kind) {
      case 'NEW_TARGET':
        { this._match('NEW_TARGET'); this._match('.'); const _0_3 = this.parseProperty(); return items; }
  
      case 'IMPORT_META':
        { this._match('IMPORT_META'); this._match('.'); const _1_3 = this.parseProperty(); return items; }
  
    default:
      this._error('Expected MetaProperty, got ' + this.la.kind);
  }
  },
  
  parseObject() {
  this._match('{');
    const $2 = this.parseObjAssignable();
    this._match(':');
    const $4 = this.parseExpression();
    this._match('FOR');
    const $6 = this.parseForVariables();
    this._match('FOROF');
    const $8 = this.parseExpression();
    const $9 = this.parseOptComma();
    this._match('}');
  return items;
  },
  
  parseAssignList() {
  return this.parse();
  },
  
  parseClass() {
  return this.parseCLASS();
  },
  
  parseImport() {
  this._match('IMPORT');
    const $2 = this.parseString();
  return items;
  },
  
  parseImportSpecifierList() {
  return this.parseImportSpecifier();
  },
  
  parseImportSpecifier() {
  return this.parseIdentifier();
  },
  
  parseImportDefaultSpecifier() {
  const $1 = this.parseIdentifier();
  return items;
  },
  
  parseImportNamespaceSpecifier() {
  this._match('IMPORT_ALL');
    this._match('AS');
    const $3 = this.parseIdentifier();
  return items;
  },
  
  parseExport() {
  this._match('EXPORT');
    this._match('{');
    this._match('}');
  return items;
  },
  
  parseExportSpecifierList() {
  return this.parseExportSpecifier();
  },
  
  parseExportSpecifier() {
  return this.parseIdentifier();
  },
  
  parseInvocation() {
  const $1 = this.parseValue();
    const $2 = this.parseOptFuncExist();
    const $3 = this.parseString();
  return items;
  },
  
  parseOptFuncExist() {
  switch (this.la.kind) {
      case '':
        return this._match('');
  
      case 'FUNC_EXIST':
        return this._match('FUNC_EXIST');
  
    default:
      this._error('Expected OptFuncExist, got ' + this.la.kind);
  }
  },
  
  parseArguments() {
  this._match('CALL_START');
    this._match('CALL_END');
  return items;
  },
  
  parseThis() {
  switch (this.la.kind) {
      case 'THIS':
        return this._match('THIS');
  
      case '@':
        return this._match('@');
  
    default:
      this._error('Expected This, got ' + this.la.kind);
  }
  },
  
  parseThisProperty() {
  this._match('@');
    const $2 = this.parseProperty();
  return items;
  },
  
  parseArray() {
  this._match('[');
    this._match(']');
  return items;
  },
  
  parseRangeDots() {
  switch (this.la.kind) {
      case '..':
        return this._match('..');
  
      case '...':
        return this._match('...');
  
    default:
      this._error('Expected RangeDots, got ' + this.la.kind);
  }
  },
  
  parseRange() {
  this._match('[');
    const $2 = this.parseExpression();
    const $3 = this.parseRangeDots();
    const $4 = this.parseExpression();
    this._match(']');
  return items;
  },
  
  parseSlice() {
  const $1 = this.parseExpression();
    const $2 = this.parseRangeDots();
    const $3 = this.parseExpression();
  return items;
  },
  
  parseArgList() {
  return this.parseArg();
  },
  
  parseArg() {
  return this.parseExpression();
  },
  
  parseArgElisionList() {
  return this.parseArgElision();
  },
  
  parseArgElision() {
  switch (this.la.kind) {
      case 'IDENTIFIER':
      case '@':
      case 'JS':
      case 'UNDEFINED':
      case 'NULL':
      case 'BOOL':
      case 'INFINITY':
      case 'NAN':
      case '(':
      case '[':
      case 'SUPER':
      case 'DYNAMIC_IMPORT':
      case 'DO_IIFE':
      case 'THIS':
      case 'NEW_TARGET':
      case 'IMPORT_META':
      case 'PARAM_START':
      case '->':
      case '=>':
      case '{':
      case 'NUMBER':
      case 'STRING':
      case 'STRING_START':
      case 'REGEX':
      case 'REGEX_START':
      case 'UNARY':
      case 'DO':
      case 'UNARY_MATH':
      case '-':
      case '+':
      case 'AWAIT':
      case '--':
      case '++':
      case 'IF':
      case 'UNLESS':
      case 'STATEMENT':
      case 'TRY':
      case 'WHILE':
      case 'UNTIL':
      case 'LOOP':
      case 'FOR':
      case 'SWITCH':
      case 'CLASS':
      case 'THROW':
      case 'YIELD':
      case 'DEF':
      case 'RETURN':
      case 'IMPORT':
      case 'EXPORT':
      case '...':
        return this.parseArg();
  
      case ',':
        { const _1_1 = this.parseElisions(); const _1_2 = this.parseArg(); return items; }
  
    default:
      this._error('Expected ArgElision, got ' + this.la.kind);
  }
  },
  
  parseOptElisions() {
  return this.parseOptComma();
  },
  
  parseElisions() {
  const items = [this.parseElision()];
  
  while (this._canParse('Elision')) {
    items.push(this.parseElision());
  }
  
  return items;
  },
  
  parseElision() {
  const items = [this._match(',')];
  
  while (this.la.kind === 'TERMINATOR') {
    items.push(this._match('TERMINATOR'));
  }
  
  return items;
  },
  
  parseSimpleArgs() {
  const items = [this.parseExpression()];
  
  while (this.la.kind === ',') {
    this._match(',');
    
    // Check FOLLOW set for trailing separator
    if (this._check(',', 'INDENT')) break;
    
    items.push(this.parseExpression());
  }
  
  return items;
  },
  
  parseTry() {
  this._match('TRY');
    const $2 = this.parseBlock();
  return items;
  },
  
  parseCatch() {
  this._match('CATCH');
    const $2 = this.parseIdentifier();
    const $3 = this.parseBlock();
  return items;
  },
  
  parseThrow() {
  this._match('THROW');
    const $2 = this.parseExpression();
  return items;
  },
  
  parseParenthetical() {
  this._match('(');
    const $2 = this.parseBody();
    this._match(')');
  return items;
  },
  
  parseWhileSource() {
  this._match('WHILE');
    const $2 = this.parseExpression();
  return items;
  },
  
  parseWhile() {
  const $1 = this.parseWhileSource();
    const $2 = this.parseBlock();
  return items;
  },
  
  parseLoop() {
  this._match('LOOP');
    const $2 = this.parseBlock();
  return items;
  },
  
  parseFor() {
  this._match('FOR');
    const $2 = this.parseForVariables();
    this._match('FORIN');
    const $4 = this.parseExpression();
    const $5 = this.parseBlock();
  return items;
  },
  
  parseForValue() {
  return this.parseForVar();
  },
  
  parseForVar() {
  switch (this.la.kind) {
      case 'IDENTIFIER':
        return this.parseIdentifier();
  
      case '@':
        return this.parseThisProperty();
  
      case '[':
        return this.parseArray();
  
      case '{':
        return this.parseObject();
  
    default:
      this._error('Expected ForVar, got ' + this.la.kind);
  }
  },
  
  parseForVariables() {
  return this.parseForValue();
  },
  
  parseSwitch() {
  this._match('SWITCH');
    const $2 = this.parseExpression();
    this._match('INDENT');
    const $4 = this.parseWhens();
    this._match('OUTDENT');
  return items;
  },
  
  parseWhens() {
  const items = [this.parseWhen()];
  
  while (this._canParse('When')) {
    items.push(this.parseWhen());
  }
  
  return items;
  },
  
  parseWhen() {
  this._match('LEADING_WHEN');
    const $2 = this.parseSimpleArgs();
    const $3 = this.parseBlock();
  return items;
  },
  
  parseIfBlock() {
  this._match('IF');
    const $2 = this.parseExpression();
    const $3 = this.parseBlock();
  return items;
  },
  
  parseUnlessBlock() {
  this._match('UNLESS');
    const $2 = this.parseExpression();
    const $3 = this.parseBlock();
  return items;
  },
  
  parseIf() {
  return this.parseIfBlock();
  },
  
  parseOperationLine() {
  switch (this.la.kind) {
      case 'UNARY':
        { this._match('UNARY'); const _0_2 = this.parseExpressionLine(); return items; }
  
      case 'DO':
        { this._match('DO'); const _1_2 = this.parseExpressionLine(); return items; }
  
      case 'DO_IIFE':
        { this._match('DO_IIFE'); const _2_2 = this.parseCodeLine(); return items; }
  
    default:
      this._error('Expected OperationLine, got ' + this.la.kind);
  }
  },
  
  parseOperation() {
  this._match('UNARY');
    const $2 = this.parseExpression();
  return items;
  },
  
  parseDoIife() {
  this._match('DO_IIFE');
    const $2 = this.parseCode();
  return items;
  }
};

function createParser(yyInit = {}) {
  const p = Object.create(parserInstance);
  Object.defineProperty(p, "yy", {
    value: { ...yyInit },
    enumerable: false,
    writable: true,
    configurable: true,
  });
  return p;
}

const parser = /*#__PURE__*/createParser();

export { parser };
export const Parser = createParser;
export const parse = parser.parse.bind(parser);
export default parser;