// ============================================================================
// Smart PRD Parser - Generated by Solar 1.4.0
// ============================================================================
// Beautiful hand-written-quality recursive descent parser with:
// - Direct dispatch (no table lookups)
// - Integer symbol IDs (8-12x faster)
// - Smart disambiguation (SLR-guided)
// - Minimal runtime data (~2 KB)
// - 40-120x performance vs table-driven
// ============================================================================

// ============================================================================
// Symbol Constants
// ============================================================================

const SYM_END = 1;
const SYM_ERROR = 2;
const SYM_ROOT = 3;
const SYM_BODY = 4;
const SYM_LINE = 5;
const SYM_TERMINATOR = 6;
const SYM_EXPRESSION = 7;
const SYM_EXPRESSIONLINE = 8;
const SYM_STATEMENT = 9;
const SYM_RETURN = 10;
const SYM_IMPORT = 12;
const SYM_EXPORT = 13;
const SYM_VALUE = 14;
const SYM_CODE = 15;
const SYM_OPERATION = 16;
const SYM_ASSIGN = 17;
const SYM_IF = 18;
const SYM_TRY = 19;
const SYM_WHILE = 20;
const SYM_FOR = 21;
const SYM_SWITCH = 22;
const SYM_CLASS = 23;
const SYM_THROW = 24;
const SYM_YIELD = 25;
const SYM_DEF = 26;
const SYM_IDENTIFIER = 28;
const SYM_CALL_START = 29;
const SYM_PARAMLIST = 30;
const SYM_CALL_END = 31;
const SYM_BLOCK = 32;
const SYM_CODELINE = 33;
const SYM_OPERATIONLINE = 34;
const SYM_INDENT = 36;
const SYM_OBJECT = 37;
const SYM_OUTDENT = 38;
const SYM_FROM = 39;
const SYM_PROPERTY = 41;
const SYM_ALPHANUMERIC = 43;
const SYM_NUMBER = 44;
const SYM_STRING = 45;
const SYM_STRING_START = 47;
const SYM_INTERPOLATIONS = 48;
const SYM_STRING_END = 49;
const SYM_INTERPOLATIONCHUNK = 50;
const SYM_INTERPOLATION_START = 51;
const SYM_INTERPOLATION_END = 52;
const SYM_REGEX = 53;
const SYM_REGEX_START = 55;
const SYM_INVOCATION = 56;
const SYM_REGEX_END = 57;
const SYM_REGEXWITHINDEX = 58;
const SYM_COMMA = 59;
const SYM_LITERAL = 60;
const SYM_JS = 61;
const SYM_UNDEFINED = 62;
const SYM_NULL = 63;
const SYM_BOOL = 64;
const SYM_INFINITY = 65;
const SYM_NAN = 66;
const SYM_ASSIGNABLE = 67;
const SYM_EQUALS = 68;
const SYM_ASSIGNOBJ = 69;
const SYM_OBJASSIGNABLE = 70;
const SYM_OBJRESTVALUE = 71;
const SYM_COLON = 72;
const SYM_SIMPLEOBJASSIGNABLE = 73;
const SYM_THISPROPERTY = 74;
const SYM_LBRACKET = 75;
const SYM_RBRACKET = 76;
const SYM_AT = 77;
const SYM_ELLIPSIS = 78;
const SYM_OBJSPREADEXPR = 79;
const SYM_PARENTHETICAL = 80;
const SYM_SUPER = 81;
const SYM_THIS = 82;
const SYM_OPTFUNCEXIST = 84;
const SYM_ARGUMENTS = 85;
const SYM_DYNAMIC_IMPORT = 86;
const SYM_DOT = 87;
const SYM_OPT_DOT = 88;
const SYM_PROTO = 89;
const SYM_OPT_PROTO = 90;
const SYM_INDEX_START = 91;
const SYM_INDEX_END = 92;
const SYM_INDEX_SOAK = 93;
const SYM_PARAM_START = 95;
const SYM_PARAM_END = 96;
const SYM_FUNCGLYPH = 97;
const SYM_ARROW = 98;
const SYM_FAT_ARROW = 99;
const SYM_OPTCOMMA = 100;
const SYM_PARAM = 101;
const SYM_PARAMVAR = 102;
const SYM_ARRAY = 103;
const SYM_SPLAT = 104;
const SYM_SIMPLEASSIGNABLE = 105;
const SYM_SLICE = 106;
const SYM_ES6_OPTIONAL_INDEX = 107;
const SYM_RANGE = 108;
const SYM_DOIIFE = 109;
const SYM_METAPROPERTY = 110;
const SYM_NEW_TARGET = 111;
const SYM_IMPORT_META = 112;
const SYM_LBRACE = 113;
const SYM_FORVARIABLES = 115;
const SYM_FOROF = 116;
const SYM_RBRACE = 117;
const SYM_WHEN = 118;
const SYM_OWN = 119;
const SYM_ASSIGNLIST = 120;
const SYM_EXTENDS = 122;
const SYM_IMPORTDEFAULTSPECIFIER = 124;
const SYM_IMPORTNAMESPACESPECIFIER = 125;
const SYM_IMPORTSPECIFIERLIST = 126;
const SYM_IMPORTSPECIFIER = 127;
const SYM_AS = 128;
const SYM_DEFAULT = 129;
const SYM_IMPORT_ALL = 130;
const SYM_EXPORTSPECIFIERLIST = 132;
const SYM_EXPORT_ALL = 133;
const SYM_EXPORTSPECIFIER = 134;
const SYM_ES6_OPTIONAL_CALL = 135;
const SYM_FUNC_EXIST = 136;
const SYM_ARGLIST = 137;
const SYM_ELISIONS = 139;
const SYM_ARGELISIONLIST = 140;
const SYM_OPTELISIONS = 141;
const SYM_RANGEDOTS = 142;
const SYM_DOTDOT = 143;
const SYM_ARG = 144;
const SYM_ARGELISION = 145;
const SYM_ELISION = 146;
const SYM_SIMPLEARGS = 147;
const SYM_CATCH = 149;
const SYM_FINALLY = 150;
const SYM_LPAREN = 153;
const SYM_RPAREN = 154;
const SYM_WHILESOURCE = 155;
const SYM_UNTIL = 157;
const SYM_LOOP = 158;
const SYM_FORIN = 160;
const SYM_BY = 161;
const SYM_FORFROM = 162;
const SYM_AWAIT = 163;
const SYM_FORVALUE = 164;
const SYM_FORVAR = 165;
const SYM_WHENS = 167;
const SYM_ELSE = 168;
const SYM_LEADING_WHEN = 170;
const SYM_IFBLOCK = 171;
const SYM_UNLESSBLOCK = 173;
const SYM_UNLESS = 174;
const SYM_POST_IF = 175;
const SYM_POST_UNLESS = 176;
const SYM_UNARY = 177;
const SYM_DO = 178;
const SYM_DO_IIFE = 179;
const SYM_UNARY_MATH = 180;
const SYM_MINUS = 181;
const SYM_PLUS = 182;
const SYM_DECREMENT = 183;
const SYM_INCREMENT = 184;
const SYM_QUESTION = 185;
const SYM_MATH = 186;
const SYM_POWER = 187;
const SYM_SHIFT = 188;
const SYM_COMPARE = 189;
const SYM_AMPERSAND = 190;
const SYM_CARET = 191;
const SYM_PIPE = 192;
const SYM_AND = 193;
const SYM_OR = 194;
const SYM_NULLISH = 195;
const SYM_OTHERWISE = 196;
const SYM_RELATION = 197;
const SYM_SPACE_QUESTION = 198;
const SYM_COMPOUND_ASSIGN = 199;

const SYMBOL_NAMES = {
  1: '$end',
  2: 'error',
  3: 'Root',
  4: 'Body',
  5: 'Line',
  6: 'TERMINATOR',
  7: 'Expression',
  8: 'ExpressionLine',
  9: 'Statement',
  10: 'Return',
  11: 'STATEMENT',
  12: 'Import',
  13: 'Export',
  14: 'Value',
  15: 'Code',
  16: 'Operation',
  17: 'Assign',
  18: 'If',
  19: 'Try',
  20: 'While',
  21: 'For',
  22: 'Switch',
  23: 'Class',
  24: 'Throw',
  25: 'Yield',
  26: 'Def',
  27: 'DEF',
  28: 'Identifier',
  29: 'CALL_START',
  30: 'ParamList',
  31: 'CALL_END',
  32: 'Block',
  33: 'CodeLine',
  34: 'OperationLine',
  35: 'YIELD',
  36: 'INDENT',
  37: 'Object',
  38: 'OUTDENT',
  39: 'FROM',
  40: 'IDENTIFIER',
  41: 'Property',
  42: 'PROPERTY',
  43: 'AlphaNumeric',
  44: 'NUMBER',
  45: 'String',
  46: 'STRING',
  47: 'STRING_START',
  48: 'Interpolations',
  49: 'STRING_END',
  50: 'InterpolationChunk',
  51: 'INTERPOLATION_START',
  52: 'INTERPOLATION_END',
  53: 'Regex',
  54: 'REGEX',
  55: 'REGEX_START',
  56: 'Invocation',
  57: 'REGEX_END',
  58: 'RegexWithIndex',
  59: ',',
  60: 'Literal',
  61: 'JS',
  62: 'UNDEFINED',
  63: 'NULL',
  64: 'BOOL',
  65: 'INFINITY',
  66: 'NAN',
  67: 'Assignable',
  68: '=',
  69: 'AssignObj',
  70: 'ObjAssignable',
  71: 'ObjRestValue',
  72: ':',
  73: 'SimpleObjAssignable',
  74: 'ThisProperty',
  75: '[',
  76: ']',
  77: '@',
  78: '...',
  79: 'ObjSpreadExpr',
  80: 'Parenthetical',
  81: 'Super',
  82: 'This',
  83: 'SUPER',
  84: 'OptFuncExist',
  85: 'Arguments',
  86: 'DYNAMIC_IMPORT',
  87: '.',
  88: '?.',
  89: '::',
  90: '?::',
  91: 'INDEX_START',
  92: 'INDEX_END',
  93: 'INDEX_SOAK',
  94: 'RETURN',
  95: 'PARAM_START',
  96: 'PARAM_END',
  97: 'FuncGlyph',
  98: '->',
  99: '=>',
  100: 'OptComma',
  101: 'Param',
  102: 'ParamVar',
  103: 'Array',
  104: 'Splat',
  105: 'SimpleAssignable',
  106: 'Slice',
  107: 'ES6_OPTIONAL_INDEX',
  108: 'Range',
  109: 'DoIife',
  110: 'MetaProperty',
  111: 'NEW_TARGET',
  112: 'IMPORT_META',
  113: '{',
  114: 'FOR',
  115: 'ForVariables',
  116: 'FOROF',
  117: '}',
  118: 'WHEN',
  119: 'OWN',
  120: 'AssignList',
  121: 'CLASS',
  122: 'EXTENDS',
  123: 'IMPORT',
  124: 'ImportDefaultSpecifier',
  125: 'ImportNamespaceSpecifier',
  126: 'ImportSpecifierList',
  127: 'ImportSpecifier',
  128: 'AS',
  129: 'DEFAULT',
  130: 'IMPORT_ALL',
  131: 'EXPORT',
  132: 'ExportSpecifierList',
  133: 'EXPORT_ALL',
  134: 'ExportSpecifier',
  135: 'ES6_OPTIONAL_CALL',
  136: 'FUNC_EXIST',
  137: 'ArgList',
  138: 'THIS',
  139: 'Elisions',
  140: 'ArgElisionList',
  141: 'OptElisions',
  142: 'RangeDots',
  143: '..',
  144: 'Arg',
  145: 'ArgElision',
  146: 'Elision',
  147: 'SimpleArgs',
  148: 'TRY',
  149: 'Catch',
  150: 'FINALLY',
  151: 'CATCH',
  152: 'THROW',
  153: '(',
  154: ')',
  155: 'WhileSource',
  156: 'WHILE',
  157: 'UNTIL',
  158: 'Loop',
  159: 'LOOP',
  160: 'FORIN',
  161: 'BY',
  162: 'FORFROM',
  163: 'AWAIT',
  164: 'ForValue',
  165: 'ForVar',
  166: 'SWITCH',
  167: 'Whens',
  168: 'ELSE',
  169: 'When',
  170: 'LEADING_WHEN',
  171: 'IfBlock',
  172: 'IF',
  173: 'UnlessBlock',
  174: 'UNLESS',
  175: 'POST_IF',
  176: 'POST_UNLESS',
  177: 'UNARY',
  178: 'DO',
  179: 'DO_IIFE',
  180: 'UNARY_MATH',
  181: '-',
  182: '+',
  183: '--',
  184: '++',
  185: '?',
  186: 'MATH',
  187: '**',
  188: 'SHIFT',
  189: 'COMPARE',
  190: '&',
  191: '^',
  192: '|',
  193: '&&',
  194: '||',
  195: '??',
  196: '!?',
  197: 'RELATION',
  198: 'SPACE?',
  199: 'COMPOUND_ASSIGN'
};



// ============================================================================
// Parser Class
// ============================================================================

class Parser {
  constructor() {
    this.la = null;    // Current lookahead token
    this.lexer = null; // Lexer instance
  }
  
  parse(input) {
    // Initialize lookahead
    this.la = this._nextToken();
    return this.parseRoot();
  }

  parseRoot() {
    switch (this.la.id) {
      case SYM_IDENTIFIER: case SYM_AT: case SYM_PARAM_START: case SYM_LBRACKET: case SYM_LBRACE: case SYM_NUMBER: case SYM_STRING: case SYM_STRING_START: case SYM_JS: case SYM_REGEX: case SYM_REGEX_START: case SYM_UNDEFINED: case SYM_NULL: case SYM_BOOL: case SYM_INFINITY: case SYM_NAN: case SYM_LPAREN: case SYM_SUPER: case SYM_DYNAMIC_IMPORT: case SYM_DO_IIFE: case SYM_THIS: case SYM_NEW_TARGET: case SYM_IMPORT_META: case SYM_ARROW: case SYM_FAT_ARROW: case SYM_UNARY: case SYM_DO: case SYM_UNARY_MATH: case SYM_MINUS: case SYM_PLUS: case SYM_AWAIT: case SYM_DECREMENT: case SYM_INCREMENT: case SYM_TRY: case SYM_FOR: case SYM_SWITCH: case SYM_CLASS: case SYM_THROW: case SYM_YIELD: case SYM_DEF: case SYM_IF: case SYM_UNLESS: case SYM_RETURN: case SYM_STATEMENT: case SYM_IMPORT: case SYM_EXPORT: case SYM_WHILE: case SYM_UNTIL: case SYM_LOOP: return this.parseBody();
      default:
        this._error([40, 77, 95, 75, 113, 44, 46, 47, 61, 54, 55, 62, 63, 64, 65, 66, 153, 83, 86, 179, 138, 111, 112, 98, 99, 177, 178, 180, 181, 182, 163, 183, 184, 148, 114, 166, 121, 152, 35, 27, 172, 174, 94, 11, 123, 131, 156, 157, 159], this.la.id);
    }
  }

  parseBody() {
    const items = [this.parseLine()];
    
    while (this.la.id === SYM_TERMINATOR) {
      this._match(SYM_TERMINATOR);
      
      // Check FOLLOW set for trailing separator
      if (this.la.id === SYM_END || this.la.id === SYM_TERMINATOR || this.la.id === SYM_OUTDENT || this.la.id === SYM_INTERPOLATION_END || this.la.id === SYM_RPAREN) break;
      
      items.push(this.parseLine());
    }
    
    return items;
  }

  parseLine() {
    switch (this.la.id) {
      case SYM_IDENTIFIER: case SYM_AT: case SYM_LBRACKET: case SYM_LBRACE: case SYM_NUMBER: case SYM_JS: case SYM_REGEX: case SYM_REGEX_START: case SYM_UNDEFINED: case SYM_NULL: case SYM_BOOL: case SYM_INFINITY: case SYM_NAN: case SYM_LPAREN: case SYM_SUPER: case SYM_DYNAMIC_IMPORT: case SYM_DO_IIFE: case SYM_THIS: case SYM_NEW_TARGET: case SYM_IMPORT_META: case SYM_PARAM_START: case SYM_ARROW: case SYM_FAT_ARROW: case SYM_STRING: case SYM_STRING_START: case SYM_UNARY: case SYM_DO: case SYM_UNARY_MATH: case SYM_MINUS: case SYM_PLUS: case SYM_AWAIT: case SYM_DECREMENT: case SYM_INCREMENT: case SYM_TRY: case SYM_FOR: case SYM_SWITCH: case SYM_CLASS: case SYM_THROW: case SYM_YIELD: case SYM_DEF: case SYM_IF: case SYM_UNLESS: case SYM_RETURN: case SYM_STATEMENT: case SYM_IMPORT: case SYM_EXPORT: case SYM_WHILE: case SYM_UNTIL: case SYM_LOOP: return this.parseExpression();
      default:
        this._error([40, 77, 75, 113, 44, 61, 54, 55, 62, 63, 64, 65, 66, 153, 83, 86, 179, 138, 111, 112, 95, 98, 99, 46, 47, 177, 178, 180, 181, 182, 163, 183, 184, 148, 114, 166, 121, 152, 35, 27, 172, 174, 94, 11, 123, 131, 156, 157, 159], this.la.id);
    }
  }

  parseStatement() {
    switch (this.la.id) {
      case SYM_RETURN: return this.parseReturn();
      case SYM_STATEMENT: return this._match(SYM_STATEMENT);
      case SYM_IMPORT: return this.parseImport();
      case SYM_EXPORT: return this.parseExport();
      default:
        this._error([94, 11, 123, 131], this.la.id);
    }
  }

  parseExpression() {
    switch (this.la.id) {
      case SYM_IDENTIFIER: case SYM_AT: case SYM_PARAM_START: case SYM_LBRACKET: case SYM_LBRACE: case SYM_NUMBER: case SYM_STRING: case SYM_STRING_START: case SYM_JS: case SYM_REGEX: case SYM_REGEX_START: case SYM_UNDEFINED: case SYM_NULL: case SYM_BOOL: case SYM_INFINITY: case SYM_NAN: case SYM_LPAREN: case SYM_SUPER: case SYM_DYNAMIC_IMPORT: case SYM_DO_IIFE: case SYM_THIS: case SYM_NEW_TARGET: case SYM_IMPORT_META: case SYM_ARROW: case SYM_FAT_ARROW: return this.parseValue();
      case SYM_UNARY: case SYM_DO: case SYM_UNARY_MATH: case SYM_MINUS: case SYM_PLUS: case SYM_AWAIT: case SYM_DECREMENT: case SYM_INCREMENT: case SYM_IF: case SYM_UNLESS: case SYM_STATEMENT: case SYM_TRY: case SYM_WHILE: case SYM_UNTIL: case SYM_LOOP: case SYM_FOR: case SYM_SWITCH: case SYM_CLASS: case SYM_THROW: case SYM_YIELD: case SYM_DEF: case SYM_RETURN: case SYM_IMPORT: case SYM_EXPORT: return this.parseOperation();
      default:
        this._error([40, 77, 95, 75, 113, 44, 46, 47, 61, 54, 55, 62, 63, 64, 65, 66, 153, 83, 86, 179, 138, 111, 112, 98, 99, 177, 178, 180, 181, 182, 163, 183, 184, 172, 174, 11, 148, 156, 157, 159, 114, 166, 121, 152, 35, 27, 94, 123, 131], this.la.id);
    }
  }

  parseDef() {
    // Parse common prefix: DEF Identifier
    this._match(SYM_DEF);
    const _prefix2 = this.parseIdentifier();
    
    // Disambiguate based on next token
    switch (this.la.id) {
      case SYM_CALL_START: {
        const prod0_3 = this._match(SYM_CALL_START);
        const prod0_4 = this.parseParamList();
        const prod0_5 = this._match(SYM_CALL_END);
        const prod0_6 = this.parseBlock();
        return ["def", _prefix2, prod0_4, prod0_6];
      }
      case SYM_INDENT: {
        const prod1_3 = this.parseBlock();
        return ["def", _prefix2, [], prod1_3];
      }
      default:
        this._error([27], this.la.id);
    }
  }

  parseExpressionLine() {
    switch (this.la.id) {
      case SYM_PARAM_START: case SYM_ARROW: case SYM_FAT_ARROW: return this.parseCodeLine();
      case SYM_UNARY: case SYM_DO: case SYM_DO_IIFE: return this.parseOperationLine();
      default:
        this._error([95, 98, 99, 177, 178, 179], this.la.id);
    }
  }

  parseYield() {
    // Parse common prefix: YIELD
    this._match(SYM_YIELD);
    
    // Disambiguate based on next token
    switch (this.la.id) {
      case SYM_END: case SYM_TERMINATOR: case SYM_OUTDENT: case SYM_RBRACKET: case SYM_INDEX_END: case SYM_CALL_END: case SYM_PARAM_END: case SYM_COMMA: case SYM_: case SYM_RBRACE: case SYM_WHEN: case SYM_DOTDOT: case SYM_ELLIPSIS: case SYM_BY: case SYM_POST_IF: case SYM_POST_UNLESS: case SYM_QUESTION: case SYM_MATH: case SYM_POWER: case SYM_SHIFT: case SYM_COMPARE: case SYM_AMPERSAND: case SYM_CARET: case SYM_PIPE: case SYM_AND: case SYM_OR: case SYM_NULLISH: case SYM_OTHERWISE: case SYM_RELATION: case SYM_SPACE_QUESTION: case SYM_COLON: case SYM_INTERPOLATION_END: case SYM_RPAREN: case SYM_FOROF: case SYM_FORIN: case SYM_FORFROM:
        return ["yield"];
      case SYM_IDENTIFIER: case SYM_AT: case SYM_LBRACKET: case SYM_LBRACE: case SYM_NUMBER: case SYM_JS: case SYM_REGEX: case SYM_REGEX_START: case SYM_UNDEFINED: case SYM_NULL: case SYM_BOOL: case SYM_INFINITY: case SYM_NAN: case SYM_LPAREN: case SYM_SUPER: case SYM_DYNAMIC_IMPORT: case SYM_DO_IIFE: case SYM_THIS: case SYM_NEW_TARGET: case SYM_IMPORT_META: case SYM_PARAM_START: case SYM_ARROW: case SYM_FAT_ARROW: case SYM_STRING: case SYM_STRING_START: case SYM_UNARY: case SYM_DO: case SYM_UNARY_MATH: case SYM_MINUS: case SYM_PLUS: case SYM_AWAIT: case SYM_DECREMENT: case SYM_INCREMENT: case SYM_TRY: case SYM_FOR: case SYM_SWITCH: case SYM_CLASS: case SYM_THROW: case SYM_YIELD: case SYM_DEF: case SYM_IF: case SYM_UNLESS: case SYM_RETURN: case SYM_STATEMENT: case SYM_IMPORT: case SYM_EXPORT: case SYM_WHILE: case SYM_UNTIL: case SYM_LOOP: {
        const prod1_2 = this.parseExpression();
        return ["yield", prod1_2];
      }
      case SYM_INDENT: {
        const prod2_2 = this._match(SYM_INDENT);
        const prod2_3 = this.parseObject();
        const prod2_4 = this._match(SYM_OUTDENT);
        return ["yield", prod2_3];
      }
      case SYM_FROM: {
        const prod3_2 = this._match(SYM_FROM);
        const prod3_3 = this.parseExpression();
        return ["yield-from", prod3_3];
      }
      default:
        this._error([35], this.la.id);
    }
  }

  parseBlock() {
    // Parse common prefix: INDENT
    this._match(SYM_INDENT);
    
    // Disambiguate based on next token
    switch (this.la.id) {
      case SYM_OUTDENT: {
        const prod0_2 = this._match(SYM_OUTDENT);
        return ["block"];
      }
      case SYM_IDENTIFIER: case SYM_AT: case SYM_PARAM_START: case SYM_LBRACKET: case SYM_LBRACE: case SYM_NUMBER: case SYM_STRING: case SYM_STRING_START: case SYM_JS: case SYM_REGEX: case SYM_REGEX_START: case SYM_UNDEFINED: case SYM_NULL: case SYM_BOOL: case SYM_INFINITY: case SYM_NAN: case SYM_LPAREN: case SYM_SUPER: case SYM_DYNAMIC_IMPORT: case SYM_DO_IIFE: case SYM_THIS: case SYM_NEW_TARGET: case SYM_IMPORT_META: case SYM_ARROW: case SYM_FAT_ARROW: case SYM_UNARY: case SYM_DO: case SYM_UNARY_MATH: case SYM_MINUS: case SYM_PLUS: case SYM_AWAIT: case SYM_DECREMENT: case SYM_INCREMENT: case SYM_TRY: case SYM_FOR: case SYM_SWITCH: case SYM_CLASS: case SYM_THROW: case SYM_YIELD: case SYM_DEF: case SYM_IF: case SYM_UNLESS: case SYM_RETURN: case SYM_STATEMENT: case SYM_IMPORT: case SYM_EXPORT: case SYM_WHILE: case SYM_UNTIL: case SYM_LOOP: {
        const prod1_2 = this.parseBody();
        const prod1_3 = this._match(SYM_OUTDENT);
        return ["block", ...prod1_2];
      }
      default:
        this._error([36], this.la.id);
    }
  }

  parseIdentifier() {
    switch (this.la.id) {
      case SYM_IDENTIFIER: return this._match(SYM_IDENTIFIER);
      default:
        this._error([40], this.la.id);
    }
  }

  parseProperty() {
    switch (this.la.id) {
      case SYM_PROPERTY: return this._match(SYM_PROPERTY);
      default:
        this._error([42], this.la.id);
    }
  }

  parseAlphaNumeric() {
    switch (this.la.id) {
      case SYM_NUMBER: return this._match(SYM_NUMBER);
      case SYM_STRING: case SYM_STRING_START: return this.parseString();
      default:
        this._error([44, 46, 47], this.la.id);
    }
  }

  parseString() {
    switch (this.la.id) {
      case SYM_STRING: {
        const r0_1 = this._match(SYM_STRING);
        return r0_1;
      }
      case SYM_STRING_START: {
        const r1_1 = this._match(SYM_STRING_START);
        const r1_2 = this.parseInterpolations();
        const r1_3 = this._match(SYM_STRING_END);
        return ["str", ...r1_2];
      }
      default:
        this._error([46, 47], this.la.id);
    }
  }

  parseInterpolations() {
    switch (this.la.id) {
      case SYM_INTERPOLATION_START: case SYM_STRING: case SYM_STRING_START: {
        const r0_1 = this.parseInterpolationChunk();
        return [r0_1];
      }
      default:
        this._error([51, 46, 47], this.la.id);
    }
  }

  parseInterpolationChunk() {
    switch (this.la.id) {
      case SYM_INTERPOLATION_START: {
        const r0_1 = this._match(SYM_INTERPOLATION_START);
        const r0_2 = this.parseBody();
        const r0_3 = this._match(SYM_INTERPOLATION_END);
        return r0_2;
      }
      case SYM_STRING: case SYM_STRING_START: {
        const r3_1 = this.parseString();
        return r3_1;
      }
      default:
        this._error([51, 46, 47], this.la.id);
    }
  }

  parseRegex() {
    switch (this.la.id) {
      case SYM_REGEX: {
        const r0_1 = this._match(SYM_REGEX);
        return r0_1;
      }
      case SYM_REGEX_START: {
        const r1_1 = this._match(SYM_REGEX_START);
        const r1_2 = this.parseInvocation();
        const r1_3 = this._match(SYM_REGEX_END);
        return ["regex", r1_2];
      }
      default:
        this._error([54, 55], this.la.id);
    }
  }

  parseRegexWithIndex() {
    // Parse common prefix: Regex
    const _prefix1 = this.parseRegex();
    
    // Disambiguate based on next token
    switch (this.la.id) {
      case SYM_COMMA: {
        const prod0_2 = this._match(SYM_COMMA);
        const prod0_3 = this.parseExpression();
        return ["regex-index", _prefix1, prod0_3];
      }
      case SYM_INDEX_END:
        return ["regex-index", _prefix1, null];
      default:
        this._error([54, 55], this.la.id);
    }
  }

  parseLiteral() {
    switch (this.la.id) {
      case SYM_NUMBER: case SYM_STRING: case SYM_STRING_START: return this.parseAlphaNumeric();
      case SYM_JS: return this._match(SYM_JS);
      case SYM_REGEX: case SYM_REGEX_START: return this.parseRegex();
      case SYM_UNDEFINED: return this._match(SYM_UNDEFINED);
      case SYM_NULL: return this._match(SYM_NULL);
      case SYM_BOOL: return this._match(SYM_BOOL);
      case SYM_INFINITY: return this._match(SYM_INFINITY);
      case SYM_NAN: return this._match(SYM_NAN);
      default:
        this._error([44, 46, 47, 61, 54, 55, 62, 63, 64, 65, 66], this.la.id);
    }
  }

  parseAssign() {
    // Parse common prefix: Assignable =
    const _prefix1 = this.parseAssignable();
    this._match(SYM_EQUALS);
    
    // Disambiguate based on next token
    switch (this.la.id) {
      case SYM_IDENTIFIER: case SYM_AT: case SYM_LBRACKET: case SYM_LBRACE: case SYM_NUMBER: case SYM_JS: case SYM_REGEX: case SYM_REGEX_START: case SYM_UNDEFINED: case SYM_NULL: case SYM_BOOL: case SYM_INFINITY: case SYM_NAN: case SYM_LPAREN: case SYM_SUPER: case SYM_DYNAMIC_IMPORT: case SYM_DO_IIFE: case SYM_THIS: case SYM_NEW_TARGET: case SYM_IMPORT_META: case SYM_PARAM_START: case SYM_ARROW: case SYM_FAT_ARROW: case SYM_STRING: case SYM_STRING_START: case SYM_UNARY: case SYM_DO: case SYM_UNARY_MATH: case SYM_MINUS: case SYM_PLUS: case SYM_AWAIT: case SYM_DECREMENT: case SYM_INCREMENT: case SYM_TRY: case SYM_FOR: case SYM_SWITCH: case SYM_CLASS: case SYM_THROW: case SYM_YIELD: case SYM_DEF: case SYM_IF: case SYM_UNLESS: case SYM_RETURN: case SYM_STATEMENT: case SYM_IMPORT: case SYM_EXPORT: case SYM_WHILE: case SYM_UNTIL: case SYM_LOOP: {
        const prod0_3 = this.parseExpression();
        return ["=", _prefix1, prod0_3];
      }
      case SYM_TERMINATOR: {
        const prod1_3 = this._match(SYM_TERMINATOR);
        const prod1_4 = this.parseExpression();
        return ["=", _prefix1, prod1_4];
      }
      case SYM_INDENT: {
        const prod2_3 = this._match(SYM_INDENT);
        const prod2_4 = this.parseExpression();
        const prod2_5 = this._match(SYM_OUTDENT);
        return ["=", _prefix1, prod2_4];
      }
      default:
        this._error([40, 77, 61, 62, 63, 64, 65, 66, 153, 75, 83, 86, 179, 138, 111, 112, 95, 98, 99, 113, 44, 46, 47, 54, 55], this.la.id);
    }
  }

  parseAssignObj() {
    switch (this.la.id) {
      case SYM_IDENTIFIER: case SYM_PROPERTY: case SYM_AT: case SYM_LBRACKET: case SYM_NUMBER: case SYM_STRING: case SYM_STRING_START: {
        const r0_1 = this.parseObjAssignable();
        return [r0_1, r0_1, null];
      }
      case SYM_ELLIPSIS: {
        const r1_1 = this.parseObjRestValue();
        return r1_1;
      }
      default:
        this._error([40, 42, 77, 75, 44, 46, 47, 78], this.la.id);
    }
  }

  parseSimpleObjAssignable() {
    switch (this.la.id) {
      case SYM_IDENTIFIER: return this.parseIdentifier();
      case SYM_PROPERTY: return this.parseProperty();
      case SYM_AT: return this.parseThisProperty();
      default:
        this._error([40, 42, 77], this.la.id);
    }
  }

  parseObjAssignable() {
    switch (this.la.id) {
      case SYM_IDENTIFIER: case SYM_PROPERTY: case SYM_AT: {
        const r0_1 = this.parseSimpleObjAssignable();
        return r0_1;
      }
      case SYM_LBRACKET: {
        const r1_1 = this._match(SYM_LBRACKET);
        const r1_2 = this.parseExpression();
        const r1_3 = this._match(SYM_RBRACKET);
        return ["computed", r1_2];
      }
      case SYM_NUMBER: case SYM_STRING: case SYM_STRING_START: {
        const r3_1 = this.parseAlphaNumeric();
        return r3_1;
      }
      default:
        this._error([40, 42, 77, 75, 44, 46, 47], this.la.id);
    }
  }

  parseObjRestValue() {
    // Parse common prefix: ...
    this._match(SYM_ELLIPSIS);
    
    // Disambiguate based on next token
    switch (this.la.id) {
      case SYM_IDENTIFIER: case SYM_PROPERTY: case SYM_AT: {
        const prod0_2 = this.parseSimpleObjAssignable();
        return ["...", prod0_2];
      }
      case SYM_LBRACE: case SYM_LPAREN: case SYM_SUPER: case SYM_THIS: case SYM_DYNAMIC_IMPORT: {
        const prod1_2 = this.parseObjSpreadExpr();
        return ["...", prod1_2];
      }
      default:
        this._error([78], this.la.id);
    }
  }

  parseObjSpreadExpr() {
    const items = [this.parseSimpleObjAssignable()];
    
    while (this.la.id === SYM_INDEX_SOAK) {
      this._match(SYM_INDEX_SOAK);
      
      // Check FOLLOW set for trailing separator
      if (this.la.id === SYM_ || this.la.id === SYM_FUNC_EXIST || this.la.id === SYM_CALL_START || this.la.id === SYM_DOT || this.la.id === SYM_OPT_DOT || this.la.id === SYM_PROTO || this.la.id === SYM_OPT_PROTO || this.la.id === SYM_INDEX_START || this.la.id === SYM_INDEX_SOAK || this.la.id === SYM_COMMA || this.la.id === SYM_RBRACE || this.la.id === SYM_TERMINATOR || this.la.id === SYM_INDENT || this.la.id === SYM_OUTDENT) break;
      
      items.push(this.parseSimpleObjAssignable());
    }
    
    return items;
  }

  parseReturn() {
    // Parse common prefix: RETURN
    this._match(SYM_RETURN);
    
    // Disambiguate based on next token
    switch (this.la.id) {
      case SYM_IDENTIFIER: case SYM_AT: case SYM_LBRACKET: case SYM_LBRACE: case SYM_NUMBER: case SYM_JS: case SYM_REGEX: case SYM_REGEX_START: case SYM_UNDEFINED: case SYM_NULL: case SYM_BOOL: case SYM_INFINITY: case SYM_NAN: case SYM_LPAREN: case SYM_SUPER: case SYM_DYNAMIC_IMPORT: case SYM_DO_IIFE: case SYM_THIS: case SYM_NEW_TARGET: case SYM_IMPORT_META: case SYM_PARAM_START: case SYM_ARROW: case SYM_FAT_ARROW: case SYM_STRING: case SYM_STRING_START: case SYM_UNARY: case SYM_DO: case SYM_UNARY_MATH: case SYM_MINUS: case SYM_PLUS: case SYM_AWAIT: case SYM_DECREMENT: case SYM_INCREMENT: case SYM_TRY: case SYM_FOR: case SYM_SWITCH: case SYM_CLASS: case SYM_THROW: case SYM_YIELD: case SYM_DEF: case SYM_IF: case SYM_UNLESS: case SYM_RETURN: case SYM_STATEMENT: case SYM_IMPORT: case SYM_EXPORT: case SYM_WHILE: case SYM_UNTIL: case SYM_LOOP: {
        const prod0_2 = this.parseExpression();
        return ["return", prod0_2];
      }
      case SYM_INDENT: {
        const prod1_2 = this._match(SYM_INDENT);
        const prod1_3 = this.parseObject();
        const prod1_4 = this._match(SYM_OUTDENT);
        return ["return", prod1_3];
      }
      case SYM_END: case SYM_TERMINATOR: case SYM_POST_IF: case SYM_POST_UNLESS: case SYM_OUTDENT: case SYM_INTERPOLATION_END: case SYM_RPAREN: case SYM_: case SYM_COMMA: case SYM_CALL_END: case SYM_RBRACKET:
        return ["return"];
      default:
        this._error([94], this.la.id);
    }
  }

  parseCode() {
    switch (this.la.id) {
      case SYM_PARAM_START: {
        const r0_1 = this._match(SYM_PARAM_START);
        const r0_2 = this.parseParamList();
        const r0_3 = this._match(SYM_PARAM_END);
        const r0_4 = this.parseFuncGlyph();
        const r0_5 = this.parseBlock();
        return [r0_4, r0_2, r0_5];
      }
      case SYM_ARROW: case SYM_FAT_ARROW: {
        const r1_1 = this.parseFuncGlyph();
        const r1_2 = this.parseBlock();
        return [r1_1, [], r1_2];
      }
      default:
        this._error([95, 98, 99], this.la.id);
    }
  }

  parseCodeLine() {
    switch (this.la.id) {
      case SYM_PARAM_START: {
        const r0_1 = this._match(SYM_PARAM_START);
        const r0_2 = this.parseParamList();
        const r0_3 = this._match(SYM_PARAM_END);
        const r0_4 = this.parseFuncGlyph();
        const r0_5 = this.parseLine();
        return [r0_4, r0_2, r0_5];
      }
      case SYM_ARROW: case SYM_FAT_ARROW: {
        const r1_1 = this.parseFuncGlyph();
        const r1_2 = this.parseLine();
        return [r1_1, [], r1_2];
      }
      default:
        this._error([95, 98, 99], this.la.id);
    }
  }

  parseFuncGlyph() {
    switch (this.la.id) {
      case SYM_ARROW: return this._match(SYM_ARROW);
      case SYM_FAT_ARROW: return this._match(SYM_FAT_ARROW);
      default:
        this._error([98, 99], this.la.id);
    }
  }

  parseOptComma() {
    switch (this.la.id) {
      case SYM_COMMA: return this._match(SYM_COMMA);
      default:
        this._error([59], this.la.id);
    }
  }

  parseParamList() {
    const items = [this.parseParam()];
    
    while (this.la.id === SYM_OPTCOMMA) {
      this._match(SYM_OPTCOMMA);
      
      // Check FOLLOW set for trailing separator
      if (this.la.id === SYM_CALL_END || this.la.id === SYM_PARAM_END || this.la.id === SYM_COMMA || this.la.id === SYM_ || this.la.id === SYM_TERMINATOR || this.la.id === SYM_INDENT || this.la.id === SYM_OUTDENT) break;
      
      items.push(this.parseParam());
    }
    
    return items;
  }

  parseParam() {
    switch (this.la.id) {
      case SYM_IDENTIFIER: case SYM_AT: case SYM_LBRACKET: case SYM_LBRACE: {
        const r0_1 = this.parseParamVar();
        return r0_1;
      }
      case SYM_ELLIPSIS: {
        const r1_1 = this._match(SYM_ELLIPSIS);
        const r1_2 = this.parseParamVar();
        return ["rest", r1_2];
      }
      default:
        this._error([40, 77, 75, 113, 78], this.la.id);
    }
  }

  parseParamVar() {
    switch (this.la.id) {
      case SYM_IDENTIFIER: return this.parseIdentifier();
      case SYM_AT: return this.parseThisProperty();
      case SYM_LBRACKET: return this.parseArray();
      case SYM_LBRACE: return this.parseObject();
      default:
        this._error([40, 77, 75, 113], this.la.id);
    }
  }

  parseSplat() {
    const $1 = this._match(SYM_ELLIPSIS);
    const $2 = this.parseExpression();
    return ["...", $2];
  }

  parseSimpleAssignable() {
    switch (this.la.id) {
      case SYM_IDENTIFIER: {
        const r0_1 = this.parseIdentifier();
        return r0_1;
      }
      case SYM_AT: {
        const r1_1 = this.parseThisProperty();
        return r1_1;
      }
      case SYM_PARAM_START: case SYM_LBRACKET: case SYM_LBRACE: case SYM_NUMBER: case SYM_STRING: case SYM_STRING_START: case SYM_JS: case SYM_REGEX: case SYM_REGEX_START: case SYM_UNDEFINED: case SYM_NULL: case SYM_BOOL: case SYM_INFINITY: case SYM_NAN: case SYM_LPAREN: case SYM_SUPER: case SYM_DYNAMIC_IMPORT: case SYM_DO_IIFE: case SYM_THIS: case SYM_NEW_TARGET: case SYM_IMPORT_META: case SYM_ARROW: case SYM_FAT_ARROW: {
        const r2_1 = this.parseValue();
        const r2_2 = this._match(SYM_DOT);
        const r2_3 = this.parseProperty();
        return [".", r2_1, r2_3];
      }
      default:
        this._error([40, 77, 95, 75, 113, 44, 46, 47, 61, 54, 55, 62, 63, 64, 65, 66, 153, 83, 86, 179, 138, 111, 112, 98, 99], this.la.id);
    }
  }

  parseAssignable() {
    switch (this.la.id) {
      case SYM_IDENTIFIER: case SYM_AT: case SYM_LBRACKET: case SYM_LBRACE: case SYM_NUMBER: case SYM_JS: case SYM_REGEX: case SYM_REGEX_START: case SYM_UNDEFINED: case SYM_NULL: case SYM_BOOL: case SYM_INFINITY: case SYM_NAN: case SYM_LPAREN: case SYM_SUPER: case SYM_DYNAMIC_IMPORT: case SYM_DO_IIFE: case SYM_THIS: case SYM_NEW_TARGET: case SYM_IMPORT_META: case SYM_PARAM_START: case SYM_ARROW: case SYM_FAT_ARROW: case SYM_STRING: case SYM_STRING_START: return this.parseSimpleAssignable();
      default:
        this._error([40, 77, 75, 113, 44, 61, 54, 55, 62, 63, 64, 65, 66, 153, 83, 86, 179, 138, 111, 112, 95, 98, 99, 46, 47], this.la.id);
    }
  }

  parseValue() {
    switch (this.la.id) {
      case SYM_IDENTIFIER: case SYM_AT: case SYM_JS: case SYM_UNDEFINED: case SYM_NULL: case SYM_BOOL: case SYM_INFINITY: case SYM_NAN: case SYM_LPAREN: case SYM_LBRACKET: case SYM_SUPER: case SYM_DYNAMIC_IMPORT: case SYM_DO_IIFE: case SYM_THIS: case SYM_NEW_TARGET: case SYM_IMPORT_META: case SYM_PARAM_START: case SYM_ARROW: case SYM_FAT_ARROW: case SYM_LBRACE: case SYM_NUMBER: case SYM_STRING: case SYM_STRING_START: case SYM_REGEX: case SYM_REGEX_START: return this.parseAssignable();
      default:
        this._error([40, 77, 61, 62, 63, 64, 65, 66, 153, 75, 83, 86, 179, 138, 111, 112, 95, 98, 99, 113, 44, 46, 47, 54, 55], this.la.id);
    }
  }

  parseSuper() {
    // Parse common prefix: SUPER
    this._match(SYM_SUPER);
    
    // Disambiguate based on next token
    switch (this.la.id) {
      case SYM_DOT: {
        const prod0_2 = this._match(SYM_DOT);
        const prod0_3 = this.parseProperty();
        return [".", "super", prod0_3];
      }
      case SYM_INDEX_START: {
        const prod1_2 = this._match(SYM_INDEX_START);
        const prod1_3 = this.parseExpression();
        const prod1_4 = this._match(SYM_INDEX_END);
        return ["[]", "super", prod1_3];
      }
      default:
        this._error([83], this.la.id);
    }
  }

  parseMetaProperty() {
    switch (this.la.id) {
      case SYM_NEW_TARGET: {
        const r0_1 = this._match(SYM_NEW_TARGET);
        const r0_2 = this._match(SYM_DOT);
        const r0_3 = this.parseProperty();
        return [".", "new", r0_3];
      }
      case SYM_IMPORT_META: {
        const r1_1 = this._match(SYM_IMPORT_META);
        const r1_2 = this._match(SYM_DOT);
        const r1_3 = this.parseProperty();
        return [".", "import", r1_3];
      }
      default:
        this._error([111, 112], this.la.id);
    }
  }

  parseObject() {
    // Parse common prefix: {
    this._match(SYM_LBRACE);
    
    // Disambiguate based on next token
    switch (this.la.id) {
      case SYM_: case SYM_IDENTIFIER: case SYM_PROPERTY: case SYM_AT: case SYM_LBRACKET: case SYM_NUMBER: case SYM_STRING: case SYM_STRING_START: case SYM_ELLIPSIS: case SYM_COMMA: case SYM_TERMINATOR: case SYM_INDENT: {
        const prod4_2 = this.parseAssignList();
        const prod4_3 = this.parseOptComma();
        const prod4_4 = this._match(SYM_RBRACE);
        return ["object", ...prod4_2];
      }
      default:
        this._error([113], this.la.id);
    }
  }

  parseAssignList() {
    const items = [this.parseAssignObj()];
    
    while (this.la.id === SYM_OPTCOMMA) {
      this._match(SYM_OPTCOMMA);
      
      // Check FOLLOW set for trailing separator
      if (this.la.id === SYM_ || this.la.id === SYM_COMMA || this.la.id === SYM_RBRACE || this.la.id === SYM_TERMINATOR || this.la.id === SYM_INDENT || this.la.id === SYM_OUTDENT) break;
      
      items.push(this.parseAssignObj());
    }
    
    return items;
  }

  parseClass() {
    // Parse common prefix: CLASS
    this._match(SYM_CLASS);
    
    // Disambiguate based on next token
    switch (this.la.id) {
      case SYM_END: case SYM_TERMINATOR: case SYM_OUTDENT: case SYM_RBRACKET: case SYM_INDEX_END: case SYM_CALL_END: case SYM_PARAM_END: case SYM_COMMA: case SYM_: case SYM_FOR: case SYM_RBRACE: case SYM_WHEN: case SYM_DOTDOT: case SYM_ELLIPSIS: case SYM_WHILE: case SYM_UNTIL: case SYM_BY: case SYM_POST_IF: case SYM_POST_UNLESS: case SYM_QUESTION: case SYM_PLUS: case SYM_MINUS: case SYM_MATH: case SYM_POWER: case SYM_SHIFT: case SYM_COMPARE: case SYM_AMPERSAND: case SYM_CARET: case SYM_PIPE: case SYM_AND: case SYM_OR: case SYM_NULLISH: case SYM_OTHERWISE: case SYM_RELATION: case SYM_SPACE_QUESTION: case SYM_COLON: case SYM_INTERPOLATION_END: case SYM_RPAREN: case SYM_FOROF: case SYM_FORIN: case SYM_FORFROM:
        return ["class", null, null];
      case SYM_INDENT: {
        const prod1_2 = this.parseBlock();
        return ["class", null, null, prod1_2];
      }
      case SYM_EXTENDS: {
        const prod2_2 = this._match(SYM_EXTENDS);
        const prod2_3 = this.parseExpression();
        return ["class", null, prod2_3];
      }
      case SYM_IDENTIFIER: case SYM_AT: case SYM_LBRACKET: case SYM_LBRACE: case SYM_NUMBER: case SYM_JS: case SYM_REGEX: case SYM_REGEX_START: case SYM_UNDEFINED: case SYM_NULL: case SYM_BOOL: case SYM_INFINITY: case SYM_NAN: case SYM_LPAREN: case SYM_SUPER: case SYM_DYNAMIC_IMPORT: case SYM_DO_IIFE: case SYM_THIS: case SYM_NEW_TARGET: case SYM_IMPORT_META: case SYM_PARAM_START: case SYM_ARROW: case SYM_FAT_ARROW: case SYM_STRING: case SYM_STRING_START: {
        const prod4_2 = this.parseSimpleAssignable();
        return ["class", prod4_2, null];
      }
      default:
        this._error([121], this.la.id);
    }
  }

  parseImport() {
    // Parse common prefix: IMPORT
    this._match(SYM_IMPORT);
    
    // Disambiguate based on next token
    switch (this.la.id) {
      case SYM_STRING: case SYM_STRING_START: {
        const prod0_2 = this.parseString();
        return ["import", "{}", prod0_2];
      }
      case SYM_IDENTIFIER: {
        const prod1_2 = this.parseImportDefaultSpecifier();
        const prod1_3 = this._match(SYM_FROM);
        const prod1_4 = this.parseString();
        return ["import", prod1_2, prod1_4];
      }
      case SYM_IMPORT_ALL: {
        const prod2_2 = this.parseImportNamespaceSpecifier();
        const prod2_3 = this._match(SYM_FROM);
        const prod2_4 = this.parseString();
        return ["import", prod2_2, prod2_4];
      }
      case SYM_LBRACE: {
        const prod3_2 = this._match(SYM_LBRACE);
        const prod3_3 = this._match(SYM_RBRACE);
        const prod3_4 = this._match(SYM_FROM);
        const prod3_5 = this.parseString();
        return ["import", "{}", prod3_5];
      }
      default:
        this._error([123], this.la.id);
    }
  }

  parseImportSpecifierList() {
    const items = [this._match(SYM_INDENT)];
    
    while (this.la.id === SYM_OPTCOMMA) {
      this._match(SYM_OPTCOMMA);
      
      // Check FOLLOW set for trailing separator
      if (this.la.id === SYM_ || this.la.id === SYM_COMMA || this.la.id === SYM_RBRACE || this.la.id === SYM_TERMINATOR || this.la.id === SYM_OUTDENT || this.la.id === SYM_INDENT) break;
      
      items.push(this._match(SYM_INDENT));
    }
    
    return items;
  }

  parseImportSpecifier() {
    switch (this.la.id) {
      case SYM_IDENTIFIER: {
        const r0_1 = this.parseIdentifier();
        return r0_1;
      }
      case SYM_DEFAULT: {
        const r2_1 = this._match(SYM_DEFAULT);
        return r2_1;
      }
      default:
        this._error([40, 129], this.la.id);
    }
  }

  parseImportDefaultSpecifier() {
    switch (this.la.id) {
      case SYM_IDENTIFIER: return this.parseIdentifier();
      default:
        this._error([40], this.la.id);
    }
  }

  parseImportNamespaceSpecifier() {
    const $1 = this._match(SYM_IMPORT_ALL);
    const $2 = this._match(SYM_AS);
    const $3 = this.parseIdentifier();
    return ["*", $3];
  }

  parseExport() {
    // Parse common prefix: EXPORT
    this._match(SYM_EXPORT);
    
    // Disambiguate based on next token
    switch (this.la.id) {
      case SYM_LBRACE: {
        const prod0_2 = this._match(SYM_LBRACE);
        const prod0_3 = this._match(SYM_RBRACE);
        return ["export", "{}"];
      }
      case SYM_CLASS: {
        const prod2_2 = this.parseClass();
        return ["export", prod2_2];
      }
      case SYM_DEF: {
        const prod3_2 = this.parseDef();
        return ["export", prod3_2];
      }
      case SYM_IDENTIFIER: {
        const prod4_2 = this.parseIdentifier();
        const prod4_3 = this._match(SYM_EQUALS);
        const prod4_4 = this.parseExpression();
        return ["export", ["=", prod4_2, prod4_4]];
      }
      case SYM_DEFAULT: {
        const prod7_2 = this._match(SYM_DEFAULT);
        const prod7_3 = this.parseExpression();
        return ["export-default", prod7_3];
      }
      case SYM_EXPORT_ALL: {
        const prod9_2 = this._match(SYM_EXPORT_ALL);
        const prod9_3 = this._match(SYM_FROM);
        const prod9_4 = this.parseString();
        return ["export-all", prod9_4];
      }
      default:
        this._error([131], this.la.id);
    }
  }

  parseExportSpecifierList() {
    const items = [this._match(SYM_INDENT)];
    
    while (this.la.id === SYM_OPTCOMMA) {
      this._match(SYM_OPTCOMMA);
      
      // Check FOLLOW set for trailing separator
      if (this.la.id === SYM_ || this.la.id === SYM_COMMA || this.la.id === SYM_RBRACE || this.la.id === SYM_TERMINATOR || this.la.id === SYM_OUTDENT || this.la.id === SYM_INDENT) break;
      
      items.push(this._match(SYM_INDENT));
    }
    
    return items;
  }

  parseExportSpecifier() {
    switch (this.la.id) {
      case SYM_IDENTIFIER: {
        const r0_1 = this.parseIdentifier();
        return r0_1;
      }
      case SYM_DEFAULT: {
        const r3_1 = this._match(SYM_DEFAULT);
        return r3_1;
      }
      default:
        this._error([40, 129], this.la.id);
    }
  }

  parseInvocation() {
    switch (this.la.id) {
      case SYM_IDENTIFIER: case SYM_AT: case SYM_PARAM_START: case SYM_LBRACKET: case SYM_LBRACE: case SYM_NUMBER: case SYM_STRING: case SYM_STRING_START: case SYM_JS: case SYM_REGEX: case SYM_REGEX_START: case SYM_UNDEFINED: case SYM_NULL: case SYM_BOOL: case SYM_INFINITY: case SYM_NAN: case SYM_LPAREN: case SYM_SUPER: case SYM_DYNAMIC_IMPORT: case SYM_DO_IIFE: case SYM_THIS: case SYM_NEW_TARGET: case SYM_IMPORT_META: case SYM_ARROW: case SYM_FAT_ARROW: {
        const r0_1 = this.parseValue();
        const r0_2 = this.parseOptFuncExist();
        const r0_3 = this.parseString();
        return ["tagged-template", r0_1, r0_3];
      }
      default:
        this._error([40, 77, 95, 75, 113, 44, 46, 47, 61, 54, 55, 62, 63, 64, 65, 66, 153, 83, 86, 179, 138, 111, 112, 98, 99], this.la.id);
    }
  }

  parseOptFuncExist() {
    switch (this.la.id) {
      case SYM_FUNC_EXIST: return this._match(SYM_FUNC_EXIST);
      default:
        this._error([136], this.la.id);
    }
  }

  parseArguments() {
    // Parse common prefix: CALL_START
    this._match(SYM_CALL_START);
    
    // Disambiguate based on next token
    switch (this.la.id) {
      case SYM_CALL_END: {
        const prod0_2 = this._match(SYM_CALL_END);
        return [];
      }
      case SYM_IDENTIFIER: case SYM_AT: case SYM_PARAM_START: case SYM_LBRACKET: case SYM_LBRACE: case SYM_NUMBER: case SYM_STRING: case SYM_STRING_START: case SYM_JS: case SYM_REGEX: case SYM_REGEX_START: case SYM_UNDEFINED: case SYM_NULL: case SYM_BOOL: case SYM_INFINITY: case SYM_NAN: case SYM_LPAREN: case SYM_SUPER: case SYM_DYNAMIC_IMPORT: case SYM_DO_IIFE: case SYM_THIS: case SYM_NEW_TARGET: case SYM_IMPORT_META: case SYM_ARROW: case SYM_FAT_ARROW: case SYM_UNARY: case SYM_DO: case SYM_UNARY_MATH: case SYM_MINUS: case SYM_PLUS: case SYM_AWAIT: case SYM_DECREMENT: case SYM_INCREMENT: case SYM_TRY: case SYM_FOR: case SYM_SWITCH: case SYM_CLASS: case SYM_THROW: case SYM_YIELD: case SYM_DEF: case SYM_IF: case SYM_UNLESS: case SYM_RETURN: case SYM_STATEMENT: case SYM_IMPORT: case SYM_EXPORT: case SYM_WHILE: case SYM_UNTIL: case SYM_LOOP: case SYM_ELLIPSIS: case SYM_INDENT: {
        const prod1_2 = this.parseArgList();
        const prod1_3 = this.parseOptComma();
        const prod1_4 = this._match(SYM_CALL_END);
        return prod1_2;
      }
      default:
        this._error([29], this.la.id);
    }
  }

  parseThis() {
    switch (this.la.id) {
      case SYM_THIS: return this._match(SYM_THIS);
      case SYM_AT: return this._match(SYM_AT);
      default:
        this._error([138, 77], this.la.id);
    }
  }

  parseThisProperty() {
    const $1 = this._match(SYM_AT);
    const $2 = this.parseProperty();
    return [".", "this", $2];
  }

  parseArray() {
    // Parse common prefix: [
    this._match(SYM_LBRACKET);
    
    // Disambiguate based on next token
    switch (this.la.id) {
      case SYM_RBRACKET: {
        const prod0_2 = this._match(SYM_RBRACKET);
        return ["array"];
      }
      case SYM_COMMA: {
        const prod1_2 = this.parseElisions();
        const prod1_3 = this._match(SYM_RBRACKET);
        return ["array", ...prod1_2];
      }
      case SYM_IDENTIFIER: case SYM_AT: case SYM_LBRACKET: case SYM_LBRACE: case SYM_NUMBER: case SYM_JS: case SYM_REGEX: case SYM_REGEX_START: case SYM_UNDEFINED: case SYM_NULL: case SYM_BOOL: case SYM_INFINITY: case SYM_NAN: case SYM_LPAREN: case SYM_SUPER: case SYM_DYNAMIC_IMPORT: case SYM_DO_IIFE: case SYM_THIS: case SYM_NEW_TARGET: case SYM_IMPORT_META: case SYM_PARAM_START: case SYM_ARROW: case SYM_FAT_ARROW: case SYM_STRING: case SYM_STRING_START: case SYM_UNARY: case SYM_DO: case SYM_UNARY_MATH: case SYM_MINUS: case SYM_PLUS: case SYM_AWAIT: case SYM_DECREMENT: case SYM_INCREMENT: case SYM_IF: case SYM_UNLESS: case SYM_STATEMENT: case SYM_TRY: case SYM_WHILE: case SYM_UNTIL: case SYM_LOOP: case SYM_FOR: case SYM_SWITCH: case SYM_CLASS: case SYM_THROW: case SYM_YIELD: case SYM_DEF: case SYM_RETURN: case SYM_IMPORT: case SYM_EXPORT: case SYM_ELLIPSIS: case SYM_INDENT: {
        const prod2_2 = this.parseArgElisionList();
        const prod2_3 = this.parseOptElisions();
        const prod2_4 = this._match(SYM_RBRACKET);
        return ["array", ...prod2_2, ...prod2_3];
      }
      default:
        this._error([75], this.la.id);
    }
  }

  parseRangeDots() {
    switch (this.la.id) {
      case SYM_DOTDOT: return this._match(SYM_DOTDOT);
      case SYM_ELLIPSIS: return this._match(SYM_ELLIPSIS);
      default:
        this._error([143, 78], this.la.id);
    }
  }

  parseRange() {
    const $1 = this._match(SYM_LBRACKET);
    const $2 = this.parseExpression();
    const $3 = this.parseRangeDots();
    const $4 = this.parseExpression();
    const $5 = this._match(SYM_RBRACKET);
    return [$3, $2, $4];
  }

  parseSlice() {
    switch (this.la.id) {
      case SYM_IDENTIFIER: case SYM_AT: case SYM_LBRACKET: case SYM_LBRACE: case SYM_NUMBER: case SYM_JS: case SYM_REGEX: case SYM_REGEX_START: case SYM_UNDEFINED: case SYM_NULL: case SYM_BOOL: case SYM_INFINITY: case SYM_NAN: case SYM_LPAREN: case SYM_SUPER: case SYM_DYNAMIC_IMPORT: case SYM_DO_IIFE: case SYM_THIS: case SYM_NEW_TARGET: case SYM_IMPORT_META: case SYM_PARAM_START: case SYM_ARROW: case SYM_FAT_ARROW: case SYM_STRING: case SYM_STRING_START: case SYM_UNARY: case SYM_DO: case SYM_UNARY_MATH: case SYM_MINUS: case SYM_PLUS: case SYM_AWAIT: case SYM_DECREMENT: case SYM_INCREMENT: case SYM_TRY: case SYM_FOR: case SYM_SWITCH: case SYM_CLASS: case SYM_THROW: case SYM_YIELD: case SYM_DEF: case SYM_IF: case SYM_UNLESS: case SYM_RETURN: case SYM_STATEMENT: case SYM_IMPORT: case SYM_EXPORT: case SYM_WHILE: case SYM_UNTIL: case SYM_LOOP: {
        const r0_1 = this.parseExpression();
        const r0_2 = this.parseRangeDots();
        const r0_3 = this.parseExpression();
        return [r0_2, r0_1, r0_3];
      }
      case SYM_DOTDOT: case SYM_ELLIPSIS: {
        const r2_1 = this.parseRangeDots();
        const r2_2 = this.parseExpression();
        return [r2_1, null, r2_2];
      }
      default:
        this._error([40, 77, 75, 113, 44, 61, 54, 55, 62, 63, 64, 65, 66, 153, 83, 86, 179, 138, 111, 112, 95, 98, 99, 46, 47, 177, 178, 180, 181, 182, 163, 183, 184, 148, 114, 166, 121, 152, 35, 27, 172, 174, 94, 11, 123, 131, 156, 157, 159, 143, 78], this.la.id);
    }
  }

  parseArgList() {
    const items = [this._match(SYM_INDENT)];
    
    while (this.la.id === SYM_OPTCOMMA) {
      this._match(SYM_OPTCOMMA);
      
      // Check FOLLOW set for trailing separator
      if (this.la.id === SYM_ || this.la.id === SYM_COMMA || this.la.id === SYM_CALL_END || this.la.id === SYM_TERMINATOR || this.la.id === SYM_OUTDENT || this.la.id === SYM_INDENT) break;
      
      items.push(this._match(SYM_INDENT));
    }
    
    return items;
  }

  parseArg() {
    switch (this.la.id) {
      case SYM_IDENTIFIER: case SYM_AT: case SYM_LBRACKET: case SYM_LBRACE: case SYM_NUMBER: case SYM_JS: case SYM_REGEX: case SYM_REGEX_START: case SYM_UNDEFINED: case SYM_NULL: case SYM_BOOL: case SYM_INFINITY: case SYM_NAN: case SYM_LPAREN: case SYM_SUPER: case SYM_DYNAMIC_IMPORT: case SYM_DO_IIFE: case SYM_THIS: case SYM_NEW_TARGET: case SYM_IMPORT_META: case SYM_PARAM_START: case SYM_ARROW: case SYM_FAT_ARROW: case SYM_STRING: case SYM_STRING_START: case SYM_UNARY: case SYM_DO: case SYM_UNARY_MATH: case SYM_MINUS: case SYM_PLUS: case SYM_AWAIT: case SYM_DECREMENT: case SYM_INCREMENT: case SYM_TRY: case SYM_FOR: case SYM_SWITCH: case SYM_CLASS: case SYM_THROW: case SYM_YIELD: case SYM_DEF: case SYM_IF: case SYM_UNLESS: case SYM_RETURN: case SYM_STATEMENT: case SYM_IMPORT: case SYM_EXPORT: case SYM_WHILE: case SYM_UNTIL: case SYM_LOOP: return this.parseExpression();
      case SYM_ELLIPSIS: return this.parseSplat();
      default:
        this._error([40, 77, 75, 113, 44, 61, 54, 55, 62, 63, 64, 65, 66, 153, 83, 86, 179, 138, 111, 112, 95, 98, 99, 46, 47, 177, 178, 180, 181, 182, 163, 183, 184, 148, 114, 166, 121, 152, 35, 27, 172, 174, 94, 11, 123, 131, 156, 157, 159, 78], this.la.id);
    }
  }

  parseArgElisionList() {
    const items = [this._match(SYM_INDENT)];
    
    while (this.la.id === SYM_OPTELISIONS) {
      this._match(SYM_OPTELISIONS);
      
      // Check FOLLOW set for trailing separator
      if (this.la.id === SYM_ || this.la.id === SYM_COMMA || this.la.id === SYM_RBRACKET || this.la.id === SYM_TERMINATOR || this.la.id === SYM_OUTDENT || this.la.id === SYM_INDENT) break;
      
      items.push(this._match(SYM_INDENT));
    }
    
    return items;
  }

  parseArgElision() {
    switch (this.la.id) {
      case SYM_IDENTIFIER: case SYM_AT: case SYM_JS: case SYM_UNDEFINED: case SYM_NULL: case SYM_BOOL: case SYM_INFINITY: case SYM_NAN: case SYM_LPAREN: case SYM_LBRACKET: case SYM_SUPER: case SYM_DYNAMIC_IMPORT: case SYM_DO_IIFE: case SYM_THIS: case SYM_NEW_TARGET: case SYM_IMPORT_META: case SYM_PARAM_START: case SYM_ARROW: case SYM_FAT_ARROW: case SYM_LBRACE: case SYM_NUMBER: case SYM_STRING: case SYM_STRING_START: case SYM_REGEX: case SYM_REGEX_START: case SYM_UNARY: case SYM_DO: case SYM_UNARY_MATH: case SYM_MINUS: case SYM_PLUS: case SYM_AWAIT: case SYM_DECREMENT: case SYM_INCREMENT: case SYM_IF: case SYM_UNLESS: case SYM_STATEMENT: case SYM_TRY: case SYM_WHILE: case SYM_UNTIL: case SYM_LOOP: case SYM_FOR: case SYM_SWITCH: case SYM_CLASS: case SYM_THROW: case SYM_YIELD: case SYM_DEF: case SYM_RETURN: case SYM_IMPORT: case SYM_EXPORT: case SYM_ELLIPSIS: {
        const r0_1 = this.parseArg();
        return [r0_1];
      }
      case SYM_COMMA: {
        const r1_1 = this.parseElisions();
        const r1_2 = this.parseArg();
        return [...r1_1, r1_2];
      }
      default:
        this._error([40, 77, 61, 62, 63, 64, 65, 66, 153, 75, 83, 86, 179, 138, 111, 112, 95, 98, 99, 113, 44, 46, 47, 54, 55, 177, 178, 180, 181, 182, 163, 183, 184, 172, 174, 11, 148, 156, 157, 159, 114, 166, 121, 152, 35, 27, 94, 123, 131, 78, 59], this.la.id);
    }
  }

  parseOptElisions() {
    switch (this.la.id) {
      case SYM_: case SYM_COMMA: {
        const r0_1 = this.parseOptComma();
        return [];
      }
      default:
        this._error([59], this.la.id);
    }
  }

  parseElisions() {
    switch (this.la.id) {
      case SYM_COMMA: {
        const r0_1 = this.parseElision();
        return [r0_1];
      }
      default:
        this._error([59], this.la.id);
    }
  }

  parseElision() {
    switch (this.la.id) {
      case SYM_COMMA: {
        const r0_1 = this._match(SYM_COMMA);
        return null;
      }
      default:
        this._error([59], this.la.id);
    }
  }

  parseSimpleArgs() {
    const items = [this.parseExpression()];
    
    while (this.la.id === SYM_COMMA) {
      this._match(SYM_COMMA);
      
      // Check FOLLOW set for trailing separator
      if (this.la.id === SYM_COMMA || this.la.id === SYM_INDENT) break;
      
      items.push(this.parseExpression());
    }
    
    return items;
  }

  parseTry() {
    // Parse common prefix: TRY Block
    this._match(SYM_TRY);
    const _prefix2 = this.parseBlock();
    
    // Disambiguate based on next token
    switch (this.la.id) {
      case SYM_END: case SYM_TERMINATOR: case SYM_OUTDENT: case SYM_RBRACKET: case SYM_INDEX_END: case SYM_CALL_END: case SYM_PARAM_END: case SYM_COMMA: case SYM_: case SYM_FOR: case SYM_RBRACE: case SYM_WHEN: case SYM_INDENT: case SYM_DOTDOT: case SYM_ELLIPSIS: case SYM_WHILE: case SYM_UNTIL: case SYM_BY: case SYM_POST_IF: case SYM_POST_UNLESS: case SYM_QUESTION: case SYM_PLUS: case SYM_MINUS: case SYM_MATH: case SYM_POWER: case SYM_SHIFT: case SYM_COMPARE: case SYM_AMPERSAND: case SYM_CARET: case SYM_PIPE: case SYM_AND: case SYM_OR: case SYM_NULLISH: case SYM_OTHERWISE: case SYM_RELATION: case SYM_SPACE_QUESTION: case SYM_COLON: case SYM_INTERPOLATION_END: case SYM_RPAREN: case SYM_FOROF: case SYM_FORIN: case SYM_FORFROM:
        return ["try", _prefix2];
      case SYM_CATCH: {
        const prod1_3 = this.parseCatch();
        return ["try", _prefix2, prod1_3];
      }
      case SYM_FINALLY: {
        const prod2_3 = this._match(SYM_FINALLY);
        const prod2_4 = this.parseBlock();
        return ["try", _prefix2, prod2_4];
      }
      default:
        this._error([148], this.la.id);
    }
  }

  parseCatch() {
    // Parse common prefix: CATCH
    this._match(SYM_CATCH);
    
    // Disambiguate based on next token
    switch (this.la.id) {
      case SYM_IDENTIFIER: {
        const prod0_2 = this.parseIdentifier();
        const prod0_3 = this.parseBlock();
        return [prod0_2, prod0_3];
      }
      case SYM_LBRACE: {
        const prod1_2 = this.parseObject();
        const prod1_3 = this.parseBlock();
        return [prod1_2, prod1_3];
      }
      case SYM_INDENT: {
        const prod2_2 = this.parseBlock();
        return [null, prod2_2];
      }
      default:
        this._error([151], this.la.id);
    }
  }

  parseThrow() {
    // Parse common prefix: THROW
    this._match(SYM_THROW);
    
    // Disambiguate based on next token
    switch (this.la.id) {
      case SYM_IDENTIFIER: case SYM_AT: case SYM_LBRACKET: case SYM_LBRACE: case SYM_NUMBER: case SYM_JS: case SYM_REGEX: case SYM_REGEX_START: case SYM_UNDEFINED: case SYM_NULL: case SYM_BOOL: case SYM_INFINITY: case SYM_NAN: case SYM_LPAREN: case SYM_SUPER: case SYM_DYNAMIC_IMPORT: case SYM_DO_IIFE: case SYM_THIS: case SYM_NEW_TARGET: case SYM_IMPORT_META: case SYM_PARAM_START: case SYM_ARROW: case SYM_FAT_ARROW: case SYM_STRING: case SYM_STRING_START: case SYM_UNARY: case SYM_DO: case SYM_UNARY_MATH: case SYM_MINUS: case SYM_PLUS: case SYM_AWAIT: case SYM_DECREMENT: case SYM_INCREMENT: case SYM_TRY: case SYM_FOR: case SYM_SWITCH: case SYM_CLASS: case SYM_THROW: case SYM_YIELD: case SYM_DEF: case SYM_IF: case SYM_UNLESS: case SYM_RETURN: case SYM_STATEMENT: case SYM_IMPORT: case SYM_EXPORT: case SYM_WHILE: case SYM_UNTIL: case SYM_LOOP: {
        const prod0_2 = this.parseExpression();
        return ["throw", prod0_2];
      }
      case SYM_INDENT: {
        const prod1_2 = this._match(SYM_INDENT);
        const prod1_3 = this.parseObject();
        const prod1_4 = this._match(SYM_OUTDENT);
        return ["throw", prod1_3];
      }
      default:
        this._error([152], this.la.id);
    }
  }

  parseParenthetical() {
    // Parse common prefix: (
    this._match(SYM_LPAREN);
    
    // Disambiguate based on next token
    switch (this.la.id) {
      case SYM_IDENTIFIER: case SYM_AT: case SYM_PARAM_START: case SYM_LBRACKET: case SYM_LBRACE: case SYM_NUMBER: case SYM_STRING: case SYM_STRING_START: case SYM_JS: case SYM_REGEX: case SYM_REGEX_START: case SYM_UNDEFINED: case SYM_NULL: case SYM_BOOL: case SYM_INFINITY: case SYM_NAN: case SYM_LPAREN: case SYM_SUPER: case SYM_DYNAMIC_IMPORT: case SYM_DO_IIFE: case SYM_THIS: case SYM_NEW_TARGET: case SYM_IMPORT_META: case SYM_ARROW: case SYM_FAT_ARROW: case SYM_UNARY: case SYM_DO: case SYM_UNARY_MATH: case SYM_MINUS: case SYM_PLUS: case SYM_AWAIT: case SYM_DECREMENT: case SYM_INCREMENT: case SYM_TRY: case SYM_FOR: case SYM_SWITCH: case SYM_CLASS: case SYM_THROW: case SYM_YIELD: case SYM_DEF: case SYM_IF: case SYM_UNLESS: case SYM_RETURN: case SYM_STATEMENT: case SYM_IMPORT: case SYM_EXPORT: case SYM_WHILE: case SYM_UNTIL: case SYM_LOOP: {
        const prod0_2 = this.parseBody();
        const prod0_3 = this._match(SYM_RPAREN);
        return $prod0_2.length === _prefix1 ? $prod0_2[0] : $prod0_2;
      }
      case SYM_INDENT: {
        const prod1_2 = this._match(SYM_INDENT);
        const prod1_3 = this.parseBody();
        const prod1_4 = this._match(SYM_OUTDENT);
        const prod1_5 = this._match(SYM_RPAREN);
        return $prod1_3.length === _prefix1 ? $prod1_3[0] : $prod1_3;
      }
      default:
        this._error([153], this.la.id);
    }
  }

  parseWhileSource() {
    switch (this.la.id) {
      case SYM_WHILE: {
        const r0_1 = this._match(SYM_WHILE);
        const r0_2 = this.parseExpression();
        return ["while", r0_2];
      }
      case SYM_UNTIL: {
        const r2_1 = this._match(SYM_UNTIL);
        const r2_2 = this.parseExpression();
        return ["until", r2_2];
      }
      default:
        this._error([156, 157], this.la.id);
    }
  }

  parseWhile() {
    switch (this.la.id) {
      case SYM_WHILE: case SYM_UNTIL: {
        const r0_1 = this.parseWhileSource();
        const r0_2 = this.parseBlock();
        return $r0_1.length === r0_2 ? [$r0_1[0], $r0_1[r0_1], $r0_2]   : [$r0_1[0], $r0_1[r0_1], $r0_1[r0_2], $r0_2];
      }
      case SYM_RETURN: case SYM_STATEMENT: case SYM_IMPORT: case SYM_EXPORT: {
        const r1_1 = this.parseStatement();
        const r1_2 = this.parseWhileSource();
        return $r1_2.length === r1_2 ? [$r1_2[0], $r1_2[r1_1], [$r1_1]] : [$r1_2[0], $r1_2[r1_1], $r1_2[r1_2], [$r1_1]];
      }
      case SYM_IDENTIFIER: case SYM_AT: case SYM_LBRACKET: case SYM_LBRACE: case SYM_NUMBER: case SYM_JS: case SYM_REGEX: case SYM_REGEX_START: case SYM_UNDEFINED: case SYM_NULL: case SYM_BOOL: case SYM_INFINITY: case SYM_NAN: case SYM_LPAREN: case SYM_SUPER: case SYM_DYNAMIC_IMPORT: case SYM_DO_IIFE: case SYM_THIS: case SYM_NEW_TARGET: case SYM_IMPORT_META: case SYM_PARAM_START: case SYM_ARROW: case SYM_FAT_ARROW: case SYM_STRING: case SYM_STRING_START: case SYM_UNARY: case SYM_DO: case SYM_UNARY_MATH: case SYM_MINUS: case SYM_PLUS: case SYM_AWAIT: case SYM_DECREMENT: case SYM_INCREMENT: case SYM_TRY: case SYM_FOR: case SYM_SWITCH: case SYM_CLASS: case SYM_THROW: case SYM_YIELD: case SYM_DEF: case SYM_IF: case SYM_UNLESS: case SYM_LOOP: {
        const r2_1 = this.parseExpression();
        const r2_2 = this.parseWhileSource();
        return $r2_2.length === r2_2 ? [$r2_2[0], $r2_2[r2_1], [$r2_1]] : [$r2_2[0], $r2_2[r2_1], $r2_2[r2_2], [$r2_1]];
      }
      default:
        this._error([156, 157, 94, 11, 123, 131, 40, 77, 75, 113, 44, 61, 54, 55, 62, 63, 64, 65, 66, 153, 83, 86, 179, 138, 111, 112, 95, 98, 99, 46, 47, 177, 178, 180, 181, 182, 163, 183, 184, 148, 114, 166, 121, 152, 35, 27, 172, 174, 159], this.la.id);
    }
  }

  parseLoop() {
    // Parse common prefix: LOOP
    this._match(SYM_LOOP);
    
    // Disambiguate based on next token
    switch (this.la.id) {
      case SYM_INDENT: {
        const prod0_2 = this.parseBlock();
        return ["loop", prod0_2];
      }
      case SYM_IDENTIFIER: case SYM_AT: case SYM_LBRACKET: case SYM_LBRACE: case SYM_NUMBER: case SYM_JS: case SYM_REGEX: case SYM_REGEX_START: case SYM_UNDEFINED: case SYM_NULL: case SYM_BOOL: case SYM_INFINITY: case SYM_NAN: case SYM_LPAREN: case SYM_SUPER: case SYM_DYNAMIC_IMPORT: case SYM_DO_IIFE: case SYM_THIS: case SYM_NEW_TARGET: case SYM_IMPORT_META: case SYM_PARAM_START: case SYM_ARROW: case SYM_FAT_ARROW: case SYM_STRING: case SYM_STRING_START: case SYM_UNARY: case SYM_DO: case SYM_UNARY_MATH: case SYM_MINUS: case SYM_PLUS: case SYM_AWAIT: case SYM_DECREMENT: case SYM_INCREMENT: case SYM_TRY: case SYM_FOR: case SYM_SWITCH: case SYM_CLASS: case SYM_THROW: case SYM_YIELD: case SYM_DEF: case SYM_IF: case SYM_UNLESS: case SYM_RETURN: case SYM_STATEMENT: case SYM_IMPORT: case SYM_EXPORT: case SYM_WHILE: case SYM_UNTIL: case SYM_LOOP: {
        const prod1_2 = this.parseExpression();
        return ["loop", [prod1_2]];
      }
      default:
        this._error([159], this.la.id);
    }
  }

  parseFor() {
    switch (this.la.id) {
      case SYM_FOR: {
        const r0_1 = this._match(SYM_FOR);
        const r0_2 = this.parseForVariables();
        const r0_3 = this._match(SYM_FORIN);
        const r0_4 = this.parseExpression();
        const r0_5 = this.parseBlock();
        return ["for-in"  , r0_2, r0_4, null, null, r0_5];
      }
      case SYM_IDENTIFIER: case SYM_AT: case SYM_LBRACKET: case SYM_LBRACE: case SYM_NUMBER: case SYM_JS: case SYM_REGEX: case SYM_REGEX_START: case SYM_UNDEFINED: case SYM_NULL: case SYM_BOOL: case SYM_INFINITY: case SYM_NAN: case SYM_LPAREN: case SYM_SUPER: case SYM_DYNAMIC_IMPORT: case SYM_DO_IIFE: case SYM_THIS: case SYM_NEW_TARGET: case SYM_IMPORT_META: case SYM_PARAM_START: case SYM_ARROW: case SYM_FAT_ARROW: case SYM_STRING: case SYM_STRING_START: case SYM_UNARY: case SYM_DO: case SYM_UNARY_MATH: case SYM_MINUS: case SYM_PLUS: case SYM_AWAIT: case SYM_DECREMENT: case SYM_INCREMENT: case SYM_TRY: case SYM_SWITCH: case SYM_CLASS: case SYM_THROW: case SYM_YIELD: case SYM_DEF: case SYM_IF: case SYM_UNLESS: case SYM_RETURN: case SYM_STATEMENT: case SYM_IMPORT: case SYM_EXPORT: case SYM_WHILE: case SYM_UNTIL: case SYM_LOOP: {
        const r15_1 = this.parseExpression();
        const r15_2 = this._match(SYM_FOR);
        const r15_3 = this.parseForVariables();
        const r15_4 = this._match(SYM_FORIN);
        const r15_5 = this.parseExpression();
        return ["comprehension", r15_1, [["for-in"  , r15_3, r15_5, null]], []];
      }
      default:
        this._error([114, 40, 77, 75, 113, 44, 61, 54, 55, 62, 63, 64, 65, 66, 153, 83, 86, 179, 138, 111, 112, 95, 98, 99, 46, 47, 177, 178, 180, 181, 182, 163, 183, 184, 148, 166, 121, 152, 35, 27, 172, 174, 94, 11, 123, 131, 156, 157, 159], this.la.id);
    }
  }

  parseForValue() {
    // Parse common prefix: ForVar
    const _prefix1 = this.parseForVar();
    
    // Disambiguate based on next token
    switch (this.la.id) {
      case SYM_FOROF: case SYM_FORIN: case SYM_FORFROM: case SYM_COMMA:
        return _prefix1;
      case SYM_EQUALS: {
        const prod1_2 = this._match(SYM_EQUALS);
        const prod1_3 = this.parseExpression();
        return ["default", _prefix1, prod1_3];
      }
      default:
        this._error([40, 77, 75, 113], this.la.id);
    }
  }

  parseForVar() {
    switch (this.la.id) {
      case SYM_IDENTIFIER: return this.parseIdentifier();
      case SYM_AT: return this.parseThisProperty();
      case SYM_LBRACKET: return this.parseArray();
      case SYM_LBRACE: return this.parseObject();
      default:
        this._error([40, 77, 75, 113], this.la.id);
    }
  }

  parseForVariables() {
    // Parse common prefix: ForValue
    const _prefix1 = this.parseForValue();
    
    // Disambiguate based on next token
    switch (this.la.id) {
      case SYM_FOROF: case SYM_FORIN: case SYM_FORFROM:
        return [_prefix1];
      case SYM_COMMA: {
        const prod1_2 = this._match(SYM_COMMA);
        const prod1_3 = this.parseForValue();
        return [_prefix1, prod1_3];
      }
      default:
        this._error([40, 77, 75, 113], this.la.id);
    }
  }

  parseSwitch() {
    // Parse common prefix: SWITCH
    this._match(SYM_SWITCH);
    
    // Disambiguate based on next token
    switch (this.la.id) {
      case SYM_IDENTIFIER: case SYM_AT: case SYM_LBRACKET: case SYM_LBRACE: case SYM_NUMBER: case SYM_JS: case SYM_REGEX: case SYM_REGEX_START: case SYM_UNDEFINED: case SYM_NULL: case SYM_BOOL: case SYM_INFINITY: case SYM_NAN: case SYM_LPAREN: case SYM_SUPER: case SYM_DYNAMIC_IMPORT: case SYM_DO_IIFE: case SYM_THIS: case SYM_NEW_TARGET: case SYM_IMPORT_META: case SYM_PARAM_START: case SYM_ARROW: case SYM_FAT_ARROW: case SYM_STRING: case SYM_STRING_START: case SYM_UNARY: case SYM_DO: case SYM_UNARY_MATH: case SYM_MINUS: case SYM_PLUS: case SYM_AWAIT: case SYM_DECREMENT: case SYM_INCREMENT: case SYM_TRY: case SYM_FOR: case SYM_SWITCH: case SYM_CLASS: case SYM_THROW: case SYM_YIELD: case SYM_DEF: case SYM_IF: case SYM_UNLESS: case SYM_RETURN: case SYM_STATEMENT: case SYM_IMPORT: case SYM_EXPORT: case SYM_WHILE: case SYM_UNTIL: case SYM_LOOP: {
        const prod0_2 = this.parseExpression();
        const prod0_3 = this._match(SYM_INDENT);
        const prod0_4 = this.parseWhens();
        const prod0_5 = this._match(SYM_OUTDENT);
        return ["switch", prod0_2, prod0_4, null];
      }
      case SYM_INDENT: {
        const prod2_2 = this._match(SYM_INDENT);
        const prod2_3 = this.parseWhens();
        const prod2_4 = this._match(SYM_OUTDENT);
        return ["switch", null, prod2_3, null];
      }
      default:
        this._error([166], this.la.id);
    }
  }

  parseWhens() {
    switch (this.la.id) {
      case SYM_LEADING_WHEN: {
        const r0_1 = this.parseWhen();
        return [r0_1];
      }
      default:
        this._error([170], this.la.id);
    }
  }

  parseWhen() {
    // Parse common prefix: LEADING_WHEN SimpleArgs Block
    this._match(SYM_LEADING_WHEN);
    const _prefix2 = this.parseSimpleArgs();
    const _prefix3 = this.parseBlock();
    
    // Disambiguate based on next token
    switch (this.la.id) {
      case SYM_OUTDENT: case SYM_ELSE: case SYM_LEADING_WHEN:
        return ["when", _prefix2, _prefix3];
      case SYM_TERMINATOR: {
        const prod1_4 = this._match(SYM_TERMINATOR);
        return ["when", _prefix2, _prefix3];
      }
      default:
        this._error([170], this.la.id);
    }
  }

  parseIfBlock() {
    const items = [this._match(SYM_IF)];
    
    while (this.la.id === SYM_ELSE) {
      this._match(SYM_ELSE);
      
      // Check FOLLOW set for trailing separator
      if (this.la.id === SYM_ELSE || this.la.id === SYM_END || this.la.id === SYM_TERMINATOR || this.la.id === SYM_OUTDENT || this.la.id === SYM_RBRACKET || this.la.id === SYM_INDEX_END || this.la.id === SYM_CALL_END || this.la.id === SYM_PARAM_END || this.la.id === SYM_COMMA || this.la.id === SYM_ || this.la.id === SYM_FOR || this.la.id === SYM_RBRACE || this.la.id === SYM_WHEN || this.la.id === SYM_INDENT || this.la.id === SYM_DOTDOT || this.la.id === SYM_ELLIPSIS || this.la.id === SYM_WHILE || this.la.id === SYM_UNTIL || this.la.id === SYM_BY || this.la.id === SYM_POST_IF || this.la.id === SYM_POST_UNLESS || this.la.id === SYM_QUESTION || this.la.id === SYM_PLUS || this.la.id === SYM_MINUS || this.la.id === SYM_MATH || this.la.id === SYM_POWER || this.la.id === SYM_SHIFT || this.la.id === SYM_COMPARE || this.la.id === SYM_AMPERSAND || this.la.id === SYM_CARET || this.la.id === SYM_PIPE || this.la.id === SYM_AND || this.la.id === SYM_OR || this.la.id === SYM_NULLISH || this.la.id === SYM_OTHERWISE || this.la.id === SYM_RELATION || this.la.id === SYM_SPACE_QUESTION || this.la.id === SYM_COLON || this.la.id === SYM_INTERPOLATION_END || this.la.id === SYM_RPAREN || this.la.id === SYM_FOROF || this.la.id === SYM_FORIN || this.la.id === SYM_FORFROM) break;
      
      items.push(this._match(SYM_IF));
    }
    
    return items;
  }

  parseUnlessBlock() {
    // Parse common prefix: UNLESS Expression Block
    this._match(SYM_UNLESS);
    const _prefix2 = this.parseExpression();
    const _prefix3 = this.parseBlock();
    
    // Disambiguate based on next token
    switch (this.la.id) {
      case SYM_END: case SYM_TERMINATOR: case SYM_OUTDENT: case SYM_RBRACKET: case SYM_INDEX_END: case SYM_CALL_END: case SYM_PARAM_END: case SYM_COMMA: case SYM_: case SYM_FOR: case SYM_RBRACE: case SYM_WHEN: case SYM_INDENT: case SYM_DOTDOT: case SYM_ELLIPSIS: case SYM_WHILE: case SYM_UNTIL: case SYM_BY: case SYM_POST_IF: case SYM_POST_UNLESS: case SYM_QUESTION: case SYM_PLUS: case SYM_MINUS: case SYM_MATH: case SYM_POWER: case SYM_SHIFT: case SYM_COMPARE: case SYM_AMPERSAND: case SYM_CARET: case SYM_PIPE: case SYM_AND: case SYM_OR: case SYM_NULLISH: case SYM_OTHERWISE: case SYM_RELATION: case SYM_SPACE_QUESTION: case SYM_COLON: case SYM_INTERPOLATION_END: case SYM_RPAREN: case SYM_FOROF: case SYM_FORIN: case SYM_FORFROM:
        return ["unless", _prefix2, _prefix3];
      case SYM_ELSE: {
        const prod1_4 = this._match(SYM_ELSE);
        const prod1_5 = this.parseBlock();
        return ["if", ["!", _prefix2], _prefix3, prod1_5];
      }
      default:
        this._error([174], this.la.id);
    }
  }

  parseIf() {
    switch (this.la.id) {
      case SYM_IF: {
        const r0_1 = this.parseIfBlock();
        return r0_1;
      }
      case SYM_UNLESS: {
        const r2_1 = this.parseUnlessBlock();
        return r2_1;
      }
      case SYM_RETURN: case SYM_STATEMENT: case SYM_IMPORT: case SYM_EXPORT: {
        const r3_1 = this.parseStatement();
        const r3_2 = this._match(SYM_POST_IF);
        const r3_3 = this.parseExpression();
        return ["if", r3_3, [r3_1]];
      }
      case SYM_IDENTIFIER: case SYM_AT: case SYM_LBRACKET: case SYM_LBRACE: case SYM_NUMBER: case SYM_JS: case SYM_REGEX: case SYM_REGEX_START: case SYM_UNDEFINED: case SYM_NULL: case SYM_BOOL: case SYM_INFINITY: case SYM_NAN: case SYM_LPAREN: case SYM_SUPER: case SYM_DYNAMIC_IMPORT: case SYM_DO_IIFE: case SYM_THIS: case SYM_NEW_TARGET: case SYM_IMPORT_META: case SYM_PARAM_START: case SYM_ARROW: case SYM_FAT_ARROW: case SYM_STRING: case SYM_STRING_START: case SYM_UNARY: case SYM_DO: case SYM_UNARY_MATH: case SYM_MINUS: case SYM_PLUS: case SYM_AWAIT: case SYM_DECREMENT: case SYM_INCREMENT: case SYM_TRY: case SYM_FOR: case SYM_SWITCH: case SYM_CLASS: case SYM_THROW: case SYM_YIELD: case SYM_DEF: case SYM_WHILE: case SYM_UNTIL: case SYM_LOOP: {
        const r4_1 = this.parseExpression();
        const r4_2 = this._match(SYM_POST_IF);
        const r4_3 = this.parseExpression();
        return ["if", r4_3, [r4_1]];
      }
      default:
        this._error([172, 174, 94, 11, 123, 131, 40, 77, 75, 113, 44, 61, 54, 55, 62, 63, 64, 65, 66, 153, 83, 86, 179, 138, 111, 112, 95, 98, 99, 46, 47, 177, 178, 180, 181, 182, 163, 183, 184, 148, 114, 166, 121, 152, 35, 27, 156, 157, 159], this.la.id);
    }
  }

  parseOperationLine() {
    switch (this.la.id) {
      case SYM_UNARY: {
        const r0_1 = this._match(SYM_UNARY);
        const r0_2 = this.parseExpressionLine();
        return [r0_1, r0_2];
      }
      case SYM_DO: {
        const r1_1 = this._match(SYM_DO);
        const r1_2 = this.parseExpressionLine();
        return ["do-iife", r1_2];
      }
      case SYM_DO_IIFE: {
        const r2_1 = this._match(SYM_DO_IIFE);
        const r2_2 = this.parseCodeLine();
        return ["do-iife", r2_2];
      }
      default:
        this._error([177, 178, 179], this.la.id);
    }
  }

  parseOperation() {
    switch (this.la.id) {
      case SYM_UNARY: {
        const r0_1 = this._match(SYM_UNARY);
        const r0_2 = this.parseExpression();
        return [r0_1, r0_2];
      }
      case SYM_DO: {
        const r1_1 = this._match(SYM_DO);
        const r1_2 = this.parseExpression();
        return ["do-iife", r1_2];
      }
      case SYM_UNARY_MATH: {
        const r2_1 = this._match(SYM_UNARY_MATH);
        const r2_2 = this.parseExpression();
        return [r2_1, r2_2];
      }
      case SYM_MINUS: {
        const r3_1 = this._match(SYM_MINUS);
        const r3_2 = this.parseExpression();
        return ["-", r3_2];
      }
      case SYM_PLUS: {
        const r4_1 = this._match(SYM_PLUS);
        const r4_2 = this.parseExpression();
        return ["+", r4_2];
      }
      case SYM_AWAIT: {
        const r5_1 = this._match(SYM_AWAIT);
        const r5_2 = this.parseExpression();
        return ["await", r5_2];
      }
      case SYM_DECREMENT: {
        const r7_1 = this._match(SYM_DECREMENT);
        const r7_2 = this.parseSimpleAssignable();
        return ["--", r7_2, false];
      }
      case SYM_INCREMENT: {
        const r8_1 = this._match(SYM_INCREMENT);
        const r8_2 = this.parseSimpleAssignable();
        return ["++", r8_2, false];
      }
      case SYM_IDENTIFIER: case SYM_AT: case SYM_LBRACKET: case SYM_LBRACE: case SYM_NUMBER: case SYM_JS: case SYM_REGEX: case SYM_REGEX_START: case SYM_UNDEFINED: case SYM_NULL: case SYM_BOOL: case SYM_INFINITY: case SYM_NAN: case SYM_LPAREN: case SYM_SUPER: case SYM_DYNAMIC_IMPORT: case SYM_DO_IIFE: case SYM_THIS: case SYM_NEW_TARGET: case SYM_IMPORT_META: case SYM_PARAM_START: case SYM_ARROW: case SYM_FAT_ARROW: case SYM_STRING: case SYM_STRING_START: {
        const r9_1 = this.parseSimpleAssignable();
        const r9_2 = this._match(SYM_DECREMENT);
        return ["--", r9_1, true];
      }
      case SYM_TRY: case SYM_FOR: case SYM_SWITCH: case SYM_CLASS: case SYM_THROW: case SYM_YIELD: case SYM_DEF: case SYM_IF: case SYM_UNLESS: case SYM_RETURN: case SYM_STATEMENT: case SYM_IMPORT: case SYM_EXPORT: case SYM_WHILE: case SYM_UNTIL: case SYM_LOOP: {
        const r11_1 = this.parseExpression();
        const r11_2 = this._match(SYM_QUESTION);
        return ["?", r11_1];
      }
      default:
        this._error([177, 178, 180, 181, 182, 163, 183, 184, 40, 77, 75, 113, 44, 61, 54, 55, 62, 63, 64, 65, 66, 153, 83, 86, 179, 138, 111, 112, 95, 98, 99, 46, 47, 148, 114, 166, 121, 152, 35, 27, 172, 174, 94, 11, 123, 131, 156, 157, 159], this.la.id);
    }
  }

  parseDoIife() {
    const $1 = this._match(SYM_DO_IIFE);
    const $2 = this.parseCode();
    return ["do-iife", $2];
  }


// ============================================================================
// Runtime Support Methods
// ============================================================================

_nextToken() {
  if (this.lexer.pos >= this.lexer.tokens.length) {
    return { id: SYM_END, kind: '$end', value: '', line: 0, column: 0 };
  }
  
  const token = this.lexer.tokens[this.lexer.pos++];
  const tokId = token[0];
  
  // Convert string token to ID if needed
  const id = typeof tokId === 'number' ? tokId : this.symbolIds[tokId] || SYM_ERROR;
  
  return {
    id: id,
    kind: SYMBOL_NAMES[id] || token[0],
    value: token[1],
    line: token[2]?.first_line || 0,
    column: token[2]?.first_column || 0,
    loc: token[2]
  };
}

_match(expected) {
  if (this.la.id !== expected) {
    this._error([expected], this.la.id);
  }
  
  const value = this.la.value;
  this.la = this._nextToken();
  return value;
}

_peek(n) {
  const savedPos = this.lexer.pos;
  const savedLa = this.la;
  
  let token = this.la;
  for (let i = 0; i < n; i++) {
    token = this._nextToken();
  }
  
  this.lexer.pos = savedPos;
  this.la = savedLa;
  
  return token.id;
}

_check(...expected) {
  return expected.includes(this.la.id);
}

_error(expectedIds, gotId) {
  const expected = expectedIds.map(id => SYMBOL_NAMES[id] || id).join(', ');
  const got = SYMBOL_NAMES[gotId] || gotId;
  const line = this.la.line + 1;
  const col = this.la.column;
  
  throw new Error(
    'Parse error at line ' + line + ', column ' + col + ': expected ' + expected + ', got ' + got
  );
}

get symbolIds() {
  // Return symbol mapping for lexer integration
  const ids = {};
  for (const [id, name] of Object.entries(SYMBOL_NAMES)) {
    ids[name] = parseInt(id);
  }
  return ids;
}
}

// ============================================================================
// Exports
// ============================================================================

const parser = new Parser();

export { parser, Parser };
export const parse = parser.parse.bind(parser);
export default parser;